/*
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 */

/*
 * guatiao-intake -- how a guatiao schema is shown.
 *
 * GENERATED BY cbindgen, from build.rs. DO NOT EDIT BY HAND.
 * Regenerate with:
 *   GUATIAO_WRITE_HEADER=1 cargo build -p guatiao-intake --features c-header
 *
 * ----------------------------------------------------------------------
 * A FORM IS A VALUE. Read one, and build one, with guatiao.h's own
 * helpers: it is a map of "sections" (a list, in display order) and
 * "fields" (hints keyed by a field's path). Nothing here is needed to
 * read it.
 *
 * These three functions are the judgement -- the part two renderers would
 * otherwise each get differently: whether a form fits its schema, how its
 * fields are grouped and ordered, and whether one is showing.
 *
 * guatiao_intake_layout() answers keys, not copies: everything else about a
 * field you already hold, through guatiao_intake_resolve() and the form
 * you passed in.
 * ----------------------------------------------------------------------
 */

#include "guatiao.h"


#ifndef GUATIAO_INTAKE_H
#define GUATIAO_INTAKE_H

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

/*
 Between a field's key and one of its payload fields.
 */
#define SEPARATOR '.'

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/*
 Whether `form` fits `schema`.

 `GUATIAO_ERR_BAD_VALUE` when it does not, and `out_error` — which may be
 null — receives a map: `kind` (`malformed`, `unknown_field`,
 `duplicate_section`, `condition_refused` or `cyclic_condition`), `at`,
 whichever of `path`, `id`, `field` and `expected` apply, and a
 `message`. It never carries a value the form compares with.

 `GUATIAO_ERR_ALLOC` when `out_error` was asked for and `alloc` cannot
 build it: the verdict is known, and the allocator is what to fix
 first. Pass a null `out_error` for the verdict alone.

 # Safety

 Every non-null pointer addresses what its type says, and `out_error`
 addresses writable storage for one value.
 */
guatiao_status guatiao_intake_check(const guatiao_value *schema,
                                    const guatiao_value *form,
                                    const guatiao_alloc *alloc,
                                    guatiao_value *out_error);

/*
 The schema's fields grouped into sections and put in order.

 Writes a list of `{ "section": <map or null>, "fields": [key, …] }` to
 `out`, built through `alloc` and freed with `guatiao_value_free`. The
 rules are `guatiao_intake::layout`'s: declared sections in order, the
 default section first unless the form places it, explicit `x-order`
 ahead of declaration order, empty groups left out.

 # Safety

 Every non-null pointer addresses what its type says, and `out`
 addresses writable storage for one value.
 */
guatiao_status guatiao_intake_layout(const guatiao_value *schema,
                                     const guatiao_value *form,
                                     const guatiao_alloc *alloc,
                                     guatiao_value *out);

/*
 The form a schema implies, for when nobody wrote one.

 An object is a form: the schema already says which section each field
 belongs to, so a renderer with no form still has one to draw. What
 comes back carries one section per distinct `x-section` in
 first-appearance order, **ids only** -- what a section is called is a
 form's business and a schema has no opinion -- plus each member's own
 form where there is something in it. A schema that groups nothing
 gives an empty map, which is a complete form.

 `out` receives a value the **caller owns** and frees with
 `guatiao_value_free`.

 # Safety

 Every non-null pointer addresses what its type says, and `out`
 addresses writable storage for one value.
 */
guatiao_status guatiao_intake_for_schema(const guatiao_value *schema,
                                         const guatiao_alloc *alloc,
                                         guatiao_value *out);

/*
 The form to show the field at `path` with: **the one the form
 assigns, or the one its schema implies**.

 The question a renderer asks. Assignment wins, because somebody wrote
 it down; where nobody did, the member's schema still groups its
 fields.

 **A field with no form and no members is not an error**: `out` is left
 ABSENT and the status is `GUATIAO_OK`, which is what a lookup that
 found nothing answers everywhere else here. So is a path naming no
 field.

 `out` receives a value the **caller owns**, whichever way it was
 reached.

 # Safety

 Every non-null pointer addresses what its type says, `path` is a
 readable view, and `out` addresses writable storage for one value.
 */
guatiao_status guatiao_intake_form_for(const guatiao_value *form,
                                       const guatiao_value *schema,
                                       guatiao_str path,
                                       const guatiao_alloc *alloc,
                                       guatiao_value *out);

/*
 Whether the field under `key` is shown, given the `values` entered so
 far. Writes the answer through `out`.

 The rules are `guatiao_intake::is_visible`'s: no condition is shown; a
 condition is met when the field it reads is itself shown and holds the
 value; a field holding nothing reads as its schema default.

 `GUATIAO_ERR_NOT_FOUND` when `key` -- or a key a condition reads --
 names no field the schema declares, and `out` is then not written.

 # Safety

 Every non-null pointer addresses what its type says, `key` is a readable
 view, and `out` addresses writable storage for one `bool`.
 */
guatiao_status guatiao_intake_is_visible(const guatiao_value *schema,
                                         const guatiao_value *form,
                                         guatiao_str key,
                                         const guatiao_value *values,
                                         bool *out);

/*
 The value at `path` inside `value`, or null.

 `agent[1].name[home].host`: a dot is a member, a bracket is a list
 position or a map key, and which one a bracket means is decided by
 what it is applied to. A path that names nothing answers null, and so
 does one that is not a path at all — the two are the same answer to a
 C caller, which is why the grammar's byte offsets stay on the Rust
 side.

 **This walks a VALUE and asks no schema.** For what the schema says
 about a path, use `guatiao_intake_resolve`.

 The result **borrows from `value`** and is valid for as long as it is.
 Nothing is allocated, so nothing is freed.

 # Safety

 `value` addresses a well-formed value, and `path` a readable view.
 */
const guatiao_value *guatiao_intake_path_get(const guatiao_value *value, guatiao_str path);

/*
 The field governing a flat key, or null.

 Follows one level of projection, so `auth.password` answers the arm
 field's own field rather than the `auth` field. Every per-field flag
 a caller wants — required, advanced, sensitive, the title — is read
 off the value this hands back, so the boundary needs one lookup rather
 than one export per flag.

 The result **borrows from `schema`** and is valid for as long as it is.

 # Safety

 `schema` addresses a well-formed value, and `key` a readable view.
 */
const guatiao_value *guatiao_intake_resolve(const guatiao_value *schema, guatiao_str key);

/*
 The flat keys one field projects onto, as a list of strings.

 Takes the schema and a key rather than a field, because **a field's
 name is not inside the field**: it is the key it is filed under in
 `properties`, so a bare pointer to a field's schema cannot say what it
 is called. Same for the three below.

 `out` is written the absent marker on entry, so a failed call leaves
 it ABSENT. A null or unusable allocator is `GUATIAO_ERR_ALLOC`.

 # Safety

 `schema` addresses a well-formed value, `key` a readable view, and
 `out` writable storage for one value.
 */
guatiao_status guatiao_intake_flat_keys(const guatiao_value *schema,
                                        guatiao_str key,
                                        const guatiao_alloc *alloc,
                                        guatiao_value *out);

/*
 Writes a tagged value into a flat store of `key -> text`.

 `GUATIAO_ERR_WRONG_KIND` when the key names no field, the field is not
 a variant, or the value is not a map — all of which are the same "it
 does not apply" the Rust side reports as `false`.

 `out` is written the absent marker on entry, so a failed call leaves
 it ABSENT. A null or unusable allocator is `GUATIAO_ERR_ALLOC`.

 # Safety

 Every non-null pointer addresses what its type says, `key` is a
 readable view, and `out` addresses writable storage for one value.
 */
guatiao_status guatiao_intake_flatten(const guatiao_value *schema,
                                      guatiao_str key,
                                      const guatiao_value *value,
                                      const guatiao_alloc *alloc,
                                      guatiao_value *out);

/*
 Rebuilds a tagged value from a flat store.

 The reverse of [`guatiao_intake_flatten`], and the round trip is what
 makes the projection usable: a front end reads text, hands it back, and
 gets the value the schema describes.

 `out` is written the absent marker on entry, so a failed call leaves
 it ABSENT. A null or unusable allocator is `GUATIAO_ERR_ALLOC`.

 # Safety

 As for [`guatiao_intake_flatten`]. `flat` is a map whose values are all
 strings; one that is not answers `GUATIAO_ERR_WRONG_KIND`.
 */
guatiao_status guatiao_intake_unflatten(const guatiao_value *schema,
                                        guatiao_str key,
                                        const guatiao_value *flat,
                                        const guatiao_alloc *alloc,
                                        guatiao_value *out);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* GUATIAO_INTAKE_H */


/* ---- what this library writes onto a schema field -------------------- */

#define GUATIAO_INTAKE_KEY_X_SECTION "x-section"
#define GUATIAO_INTAKE_KEY_X_ORDER "x-order"
#define GUATIAO_INTAKE_KEY_X_ADVANCED "x-advanced"
