// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

//! Renders `include/greeter_kind.h`: every kind table this crate declares,
//! as a C struct a library written in C can fill.
//!
//! **The pattern a consumer copies.** A kind's table is generated by
//! `#[guatiao::kind]`, and a header generator that parses source cannot
//! see a generated struct — unless it expands macros first. cbindgen can,
//! given three things this script and `cbindgen.toml` supply:
//!
//! 1. `[parse.expand] crates = ["greeter_kind"]` — cbindgen runs
//!    `cargo rustc -- -Zunpretty=expanded` for this crate and parses the
//!    output. The stable compiler refuses that flag unless
//!    `RUSTC_BOOTSTRAP=1` is in the environment, and cbindgen does not set
//!    it, so this script sets it around the render and nowhere else.
//! 2. `[export] include = [..]` naming every table. cbindgen emits only
//!    what an exported function references, and a kind crate exports no
//!    functions; naming the tables is what makes them appear.
//! 3. `parse_deps = false` with a `[export.rename]` table mapping
//!    guatiao's type names onto the names `guatiao.h` declares, which the
//!    header includes. The tables are rendered against those names and
//!    guatiao's own types are not emitted a second time.
//!
//! The expansion re-enters cargo from inside a build script. It runs in
//! its own target directory (`CARGO_EXPAND_TARGET_DIR`) so it never waits
//! on the lock the outer build holds.
//!
//! # Refreshing the committed copy
//!
//! ```text
//! GUATIAO_WRITE_HEADER=1 cargo build -p greeter_kind --features c-header
//! ```
//!
//! The render goes to `OUT_DIR` on every `c-header` build, and
//! `tests/header_is_current.rs` compares the committed file against it.

fn main() {
    println!("cargo::rerun-if-changed=src");
    println!("cargo::rerun-if-changed=cbindgen.toml");
    println!("cargo::rerun-if-changed=Cargo.toml");
    println!("cargo::rerun-if-env-changed=GUATIAO_WRITE_HEADER");

    #[cfg(feature = "c-header")]
    render();
}

#[cfg(feature = "c-header")]
fn render() {
    use std::path::PathBuf;

    let crate_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("cargo sets this"));
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("cargo sets this"));

    // The expansion needs a nightly-only flag; this is the documented way
    // to have the stable compiler accept it, scoped to the render.
    // SAFETY: a build script is single-threaded at this point, and the
    // variables are read by the child cargo cbindgen spawns.
    unsafe {
        std::env::set_var("RUSTC_BOOTSTRAP", "1");
        std::env::set_var("CARGO_EXPAND_TARGET_DIR", out_dir.join("expand"));
    }

    let config = cbindgen::Config::from_file(crate_dir.join("cbindgen.toml"))
        .expect("cbindgen.toml is committed beside this script");
    let generated = match cbindgen::generate_with_config(&crate_dir, config) {
        Ok(g) => g,
        Err(e) => {
            println!("cargo::warning=cbindgen could not render the kind header: {e}");
            return;
        }
    };

    let rendered = out_dir.join("greeter_kind.h");
    generated.write_to_file(&rendered);
    println!(
        "cargo::rustc-env=GREETER_KIND_GENERATED_HEADER={}",
        rendered.display()
    );
    if std::env::var_os("GUATIAO_WRITE_HEADER").is_some() {
        generated.write_to_file(crate_dir.join("include").join("greeter_kind.h"));
    }
}
