/*
 * guatiao-form -- how a guatiao schema is shown.
 *
 * GENERATED BY cbindgen, from build.rs. DO NOT EDIT BY HAND.
 * Regenerate with:
 *   GUATIAO_WRITE_HEADER=1 cargo build -p guatiao-form --features c-header
 *
 * ----------------------------------------------------------------------
 * A FORM IS A VALUE. Read one, and build one, with guatiao.h's own
 * helpers: it is a map of "sections" (a list, in display order) and
 * "fields" (hints keyed by a field's path). Nothing here is needed to
 * read it.
 *
 * These three functions are the judgement -- the part two renderers would
 * otherwise each get differently: whether a form fits its schema, how its
 * fields are grouped and ordered, and whether one is showing.
 *
 * guatiao_form_layout() answers keys, not copies: everything else about a
 * field you already hold, through guatiao_schema_resolve() and the form
 * you passed in.
 * ----------------------------------------------------------------------
 */

#include "guatiao.h"


#ifndef GUATIAO_FORM_H
#define GUATIAO_FORM_H

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/*
 Whether `form` fits `schema`.

 `GUATIAO_ERR_BAD_VALUE` when it does not, and `out_error` — which may be
 null — receives a map: `kind` (`malformed`, `unknown_field`,
 `duplicate_section`, `condition_refused` or `cyclic_condition`), `at`,
 whichever of `path`, `id`, `field` and `expected` apply, and a
 `message`. It never carries a value the form compares with.

 # Safety

 Every non-null pointer addresses what its type says, and `out_error`
 addresses writable storage for one value.
 */
guatiao_status guatiao_form_check(const guatiao_value *schema,
                                  const guatiao_value *form,
                                  const guatiao_alloc *alloc,
                                  guatiao_value *out_error);

/*
 The schema's fields grouped into sections and put in order.

 Writes a list of `{ "section": <map or null>, "fields": [key, …] }` to
 `out`, built through `alloc` and freed with `guatiao_value_free`. The
 rules are `guatiao_form::layout`'s: declared sections in order, the
 default section first unless the form places it, explicit `x-order`
 ahead of declaration order, empty groups left out.

 # Safety

 Every non-null pointer addresses what its type says, and `out`
 addresses writable storage for one value.
 */
guatiao_status guatiao_form_layout(const guatiao_value *schema,
                                   const guatiao_value *form,
                                   const guatiao_alloc *alloc,
                                   guatiao_value *out);

/*
 Whether the field under `key` is shown, given the `values` entered so
 far. Writes the answer through `out`.

 The rules are `guatiao_form::is_visible`'s: no condition is shown; a
 condition is met when the field it reads is itself shown and holds the
 value; a field holding nothing reads as its schema default.

 # Safety

 Every non-null pointer addresses what its type says, `key` is a readable
 view, and `out` addresses writable storage for one `bool`.
 */
guatiao_status guatiao_form_is_visible(const guatiao_value *schema,
                                       const guatiao_value *form,
                                       guatiao_str key,
                                       const guatiao_value *values,
                                       bool *out);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* GUATIAO_FORM_H */
