/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/. */

/*
 * greeter_kind -- the kind tables, for a library written in C.
 *
 * GENERATED BY cbindgen, from build.rs, by expanding #[guatiao::kind].
 * DO NOT EDIT BY HAND. Regenerate with:
 *   GUATIAO_WRITE_HEADER=1 cargo build -p greeter_kind --features c-header
 *
 * A C library fills one of these tables -- `header.struct_size` is
 * sizeof the table as compiled here, `header.floor_hash` is the
 * *_FLOOR_HASH macro beside it -- and offers it through a
 * guatiao_provider_info's `tables`, from a guatiao_library_entry of its
 * own. Every slot takes the provider's `ctx` first; an object kind's
 * table starts with `destroy`, which whoever holds the object last calls.
 */


#ifndef GREETER_KIND_H
#define GREETER_KIND_H

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <guatiao.h>

typedef struct greeter_vtable {
  guatiao_kind_header header;
  guatiao_status (*greet)(void *ctx, guatiao_str name, guatiao_map *out, guatiao_provider_error *err);
  guatiao_status (*shout)(void *ctx, guatiao_str name, guatiao_string *out);
  guatiao_status (*start)(void *ctx,
                          guatiao_object listener,
                          guatiao_object *out,
                          guatiao_provider_error *err);
} greeter_vtable;
/*
 FNV-1a over the shape and the required signatures, as a
 literal, so a C header generator can render it: what a C
 implementation writes into the table's header.
 */
#define greeter_vtable_FLOOR_HASH 2695856491

typedef struct counter_vtable {
  guatiao_kind_header header;
  guatiao_status (*count)(void *ctx, int64_t *out);
} counter_vtable;
/*
 FNV-1a over the shape and the required signatures, as a
 literal, so a C header generator can render it: what a C
 implementation writes into the table's header.
 */
#define counter_vtable_FLOOR_HASH 1227528937

typedef struct conversation_vtable {
  guatiao_kind_header header;
  void (*destroy)(void *ctx);
  guatiao_status (*say)(void *ctx, guatiao_str what, guatiao_provider_error *err);
  guatiao_status (*read)(void *ctx, guatiao_bytes_mut dst, int64_t *out);
  guatiao_status (*turns)(void *ctx, int64_t *out);
} conversation_vtable;
/*
 FNV-1a over the shape and the required signatures, as a
 literal, so a C header generator can render it: what a C
 implementation writes into the table's header.
 */
#define conversation_vtable_FLOOR_HASH 2769624503

typedef struct listener_vtable {
  guatiao_kind_header header;
  void (*destroy)(void *ctx);
  guatiao_status (*heard)(void *ctx, guatiao_str what);
} listener_vtable;
/*
 FNV-1a over the shape and the required signatures, as a
 literal, so a C header generator can render it: what a C
 implementation writes into the table's header.
 */
#define listener_vtable_FLOOR_HASH 1867921573

#endif  /* GREETER_KIND_H */
