/*
 * guatiao-serde -- reading and writing a guatiao value as a document.
 *
 * GENERATED BY cbindgen, from build.rs. DO NOT EDIT BY HAND.
 * Regenerate with:
 *   GUATIAO_WRITE_HEADER=1 cargo build -p guatiao-serde *       --features c-header,json,toml,yaml
 *
 * ----------------------------------------------------------------------
 * EMITTING ANSWERS A VALUE, NOT A STRING.
 *
 * guatiao_json_emit() and friends write a guatiao_value holding the text,
 * which you release with guatiao_value_free() like any other tree. There
 * is no second thing to free, and the answer carries the allocator that
 * made it.
 *
 * The `how` argument is one integer: its LOW BYTE chooses how a byte
 * string is spelled where the format has none, and the bits above it are
 * flags. Zero is the default in every position.
 * ----------------------------------------------------------------------
 */

#include "guatiao.h"


#ifndef GUATIAO_SERDE_H
#define GUATIAO_SERDE_H

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

/*
 How a byte string is spelled where the format has none. The **low
 byte** of the `how` argument.
 */
#define GUATIAO_BYTES_DATA_URI 0

/*
 Bare base64 in a string, with nothing to recognise it by.
 */
#define GUATIAO_BYTES_BASE64 1

/*
 An array of numbers: unambiguous, at about four characters a byte.
 */
#define GUATIAO_BYTES_ARRAY 2

/*
 Refuse to write one at all.
 */
#define GUATIAO_BYTES_REFUSE 3

/*
 Turn a `data:;base64,…` string back into bytes when reading.

 Off unless asked: on, a byte string survives a round trip through a
 format with none; also on, a string somebody wrote that happens to
 look like a data URI silently becomes bytes.
 */
#define GUATIAO_READ_DATA_URIS (1 << 8)

/*
 Indent the output for a person to read. JSON only; the others are
 already written for a reader.
 */
#define GUATIAO_PRETTY (1 << 9)

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/*
 Reads a JSON document into a value, built through `alloc`.

 # Safety

 `text` is a readable view for this call, `alloc` is null or a complete
 allocator outliving every tree built through it, and `out` addresses
 writable storage for one value whose previous contents are the
 caller's to have freed.
 */
guatiao_status guatiao_json_parse(guatiao_str text,
                                  uint32_t how,
                                  const guatiao_alloc *alloc,
                                  guatiao_value *out);

/*
 Writes a value as a JSON document.

 **`out` receives a value holding the text**, released with
 `guatiao_value_free` like any other tree — so there is no second thing
 to free and no second way to get it wrong.

 # Safety

 `value` addresses a well-formed value, `alloc` is null or a complete
 allocator, and `out` addresses writable storage for one value whose
 previous contents are the caller's to have freed.
 */
guatiao_status guatiao_json_emit(const guatiao_value *value,
                                 uint32_t how,
                                 const guatiao_alloc *alloc,
                                 guatiao_value *out);

/*
 The same, indented for a person to read.

 Its own function rather than a flag, because JSON is the only format
 here with two spellings — the others are already written for a reader.

 # Safety

 As [`guatiao_json_emit`].
 */
guatiao_status guatiao_json_emit_pretty(const guatiao_value *value,
                                        uint32_t how,
                                        const guatiao_alloc *alloc,
                                        guatiao_value *out);

/*
 Reads a TOML document into a value, built through `alloc`.

 # Safety

 As [`guatiao_json_parse`].
 */
guatiao_status guatiao_toml_parse(guatiao_str text,
                                  uint32_t how,
                                  const guatiao_alloc *alloc,
                                  guatiao_value *out);

/*
 Writes a value as a TOML document.

 **A TOML document is a table**, so a value that is not a map is
 refused with `GUATIAO_ERR_WRONG_KIND` rather than wrapped in a key it
 never had.

 # Safety

 As [`guatiao_json_emit`].
 */
guatiao_status guatiao_toml_emit(const guatiao_value *value,
                                 uint32_t how,
                                 const guatiao_alloc *alloc,
                                 guatiao_value *out);

/*
 Reads a YAML document into a value, built through `alloc`.

 # Safety

 As [`guatiao_json_parse`].
 */
guatiao_status guatiao_yaml_parse(guatiao_str text,
                                  uint32_t how,
                                  const guatiao_alloc *alloc,
                                  guatiao_value *out);

/*
 Writes a value as a YAML document.

 # Safety

 As [`guatiao_json_emit`].
 */
guatiao_status guatiao_yaml_emit(const guatiao_value *value,
                                 uint32_t how,
                                 const guatiao_alloc *alloc,
                                 guatiao_value *out);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* GUATIAO_SERDE_H */
