/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/. */

/*
 * The claim this file exists to prove: a C consumer can declare a whole
 * value tree as a static literal, read every part of it, grow one by hand
 * through its own allocator, and free it -- with NOTHING LINKED. Not one
 * symbol from the Rust side is referenced here.
 *
 * It also pins the layout from the C side. Rust asserting its own sizes
 * proves nothing about the header a consumer actually compiles against,
 * and the two are generated by different machinery.
 *
 * The header is included TWICE on purpose. The trailer that defines
 * guatiao_entry is emitted after the file's own include guard, so an
 * unguarded one would redefine everything on a second include -- and a
 * real consumer with two headers of its own including this would be the
 * one to find out.
 */

#include "guatiao.h"
#include "guatiao.h"

#include <stdio.h>
#include <string.h>

/* ---- the layout, from the C side ------------------------------------ */

/* In pointer widths, as the Rust side states them, so this compiles on
 * every target the crate builds for. */
#define P sizeof(void *)
_Static_assert(sizeof(guatiao_str) == 2 * P, "view is two words");
_Static_assert(sizeof(guatiao_bytes) == 2 * P, "view is two words");
_Static_assert(sizeof(guatiao_values) == 2 * P, "view is two words");
_Static_assert(sizeof(guatiao_entries) == 2 * P, "view is two words");

_Static_assert(sizeof(guatiao_string) == 4 * P, "owned is four words");
_Static_assert(sizeof(guatiao_buffer) == 4 * P, "owned is four words");
_Static_assert(sizeof(guatiao_list) == 4 * P, "owned is four words");
_Static_assert(sizeof(guatiao_map) == 4 * P, "owned is four words");

_Static_assert(sizeof(guatiao_payload) == 4 * P, "the union is its widest arm");
_Static_assert(sizeof(guatiao_value) == 8 + 4 * P, "tag, pad, payload");
_Static_assert(sizeof(guatiao_entry) == 4 * P + sizeof(guatiao_value), "key plus value");
_Static_assert(sizeof(guatiao_alloc) == 5 * P, "size padded to a word, ctx, three callbacks");
#undef P

_Static_assert(_Alignof(guatiao_value) == _Alignof(void *), "pointer aligned");
_Static_assert(_Alignof(guatiao_entry) == _Alignof(void *), "pointer aligned");

_Static_assert(offsetof(guatiao_value, tag) == 0, "the tag leads");
_Static_assert(offsetof(guatiao_value, _pad) == 4, "then the reserved word");
_Static_assert(offsetof(guatiao_value, payload) == 8, "then the payload");
_Static_assert(offsetof(guatiao_entry, key) == 0, "the key leads an entry");
_Static_assert(offsetof(guatiao_entry, value) == 32, "then the value inline");

_Static_assert(offsetof(guatiao_string, ptr) == 0, "ptr, len, cap, alloc");
_Static_assert(offsetof(guatiao_string, len) == 8, "ptr, len, cap, alloc");
_Static_assert(offsetof(guatiao_string, cap) == 16, "ptr, len, cap, alloc");
_Static_assert(offsetof(guatiao_string, alloc) == 24, "ptr, len, cap, alloc");

_Static_assert(offsetof(guatiao_alloc, struct_size) == 0, "size leads");
_Static_assert(offsetof(guatiao_alloc, ctx) == 8, "then ctx");
_Static_assert(offsetof(guatiao_alloc, alloc) == 16, "then the callbacks");
_Static_assert(offsetof(guatiao_alloc, free) == 24, "then the callbacks");
_Static_assert(offsetof(guatiao_alloc, release) == 32, "release is newest");

/* The tag numbers are frozen: a consumer compiled today must keep reading
   a producer built tomorrow, and that works only if numbers never move. */
_Static_assert(GUATIAO_ABSENT == 0, "tags are frozen");
_Static_assert(GUATIAO_NULL == 1, "tags are frozen");
_Static_assert(GUATIAO_BOOL == 2, "tags are frozen");
_Static_assert(GUATIAO_NUMBER == 3, "tags are frozen");
_Static_assert(GUATIAO_STRING == 4, "tags are frozen");
_Static_assert(GUATIAO_BYTES == 5, "tags are frozen");
_Static_assert(GUATIAO_LIST == 6, "tags are frozen");
_Static_assert(GUATIAO_MAP == 7, "tags are frozen");

/* Every container asks its allocator for its element type's alignment, and
   malloc guarantees only max_align_t. If that ever stopped covering it, a
   malloc-backed allocator would silently return unusable memory. */
_Static_assert(_Alignof(guatiao_value) <= _Alignof(max_align_t),
               "malloc can satisfy a list's alignment");
_Static_assert(_Alignof(guatiao_entry) <= _Alignof(max_align_t),
               "malloc can satisfy a map's alignment");

/* ---- a tree written as a literal ------------------------------------ */

/* Bytes with an embedded NUL and a byte that is not valid UTF-8: ordinary
   content for a bytes value, and unrepresentable in anything that stops at
   a terminator. */
static const uint8_t BLOB[] = {0x00, 0xff, 'x', 0x00, 'y'};

static guatiao_value LIST_ITEMS[] = {
    GUATIAO_VALUE_NUMBER_LIT("1"),
    GUATIAO_VALUE_NUMBER_LIT("2"),
};

static guatiao_entry INNER_ENTRIES[] = {
    GUATIAO_ENTRY_LIT("verify", GUATIAO_VALUE_BOOL_LIT(true)),
};

static guatiao_entry ROOT_ENTRIES[] = {
    GUATIAO_ENTRY_LIT("host", GUATIAO_VALUE_STRING_LIT("10.0.0.1")),
    /* Exactly the text, and far too big for any machine integer. */
    GUATIAO_ENTRY_LIT("huge", GUATIAO_VALUE_NUMBER_LIT(
                                  "123456789012345678901234567890")),
    GUATIAO_ENTRY_LIT("port", GUATIAO_VALUE_NUMBER_LIT("5900")),
    GUATIAO_ENTRY_LIT("exact", GUATIAO_VALUE_NUMBER_LIT("1.10")),
    GUATIAO_ENTRY_LIT("nothing", GUATIAO_VALUE_NULL_LIT),
    GUATIAO_ENTRY_LIT("blob", GUATIAO_VALUE_BYTES_LIT(BLOB)),
    GUATIAO_ENTRY_LIT("items", GUATIAO_VALUE_LIST_LIT(LIST_ITEMS)),
    GUATIAO_ENTRY_LIT("tls", GUATIAO_VALUE_MAP_LIT(INNER_ENTRIES)),
};

static guatiao_value ROOT = GUATIAO_VALUE_MAP_LIT(ROOT_ENTRIES);

static int failures = 0;

#define CHECK(cond, what)                                                 \
  do {                                                                    \
    if (!(cond)) {                                                        \
      printf("FAIL %s:%d: %s\n", __FILE__, __LINE__, (what));             \
      failures++;                                                         \
    }                                                                     \
  } while (0)

static bool str_is(guatiao_str s, const char *expect) {
  return guatiao_str_eq(s, guatiao_cstr(expect));
}

/* ---- reading the literal, with nothing linked ----------------------- */

static void read_the_literal(void) {
  const guatiao_value *v;

  CHECK(guatiao_tag_of(&ROOT) == (uint32_t)GUATIAO_MAP, "the root is a map");
  CHECK(guatiao_map_entries(&ROOT).len == 8, "eight entries");

  v = guatiao_map_find(&ROOT, guatiao_cstr("host"));
  CHECK(v != NULL, "host is there");
  CHECK(str_is(guatiao_string_text(v), "10.0.0.1"), "host reads back");
  CHECK(guatiao_number_text(v).len == 0, "a string is not a number");

  /* The headline property, from C: the exact text, whatever its size. */
  v = guatiao_map_find(&ROOT, guatiao_cstr("huge"));
  CHECK(str_is(guatiao_number_text(v), "123456789012345678901234567890"),
        "a 30-digit integer survives verbatim");
  CHECK(guatiao_int_or(v, -1) == -1,
        "and does not truncate: it is answered as not representable");

  v = guatiao_map_find(&ROOT, guatiao_cstr("exact"));
  CHECK(str_is(guatiao_number_text(v), "1.10"), "1.10 is not 1.1");
  CHECK(guatiao_int_or(v, -1) == -1, "a fractional value is not an integer");
  CHECK(guatiao_float_or(v, 0.0) > 1.09 && guatiao_float_or(v, 0.0) < 1.11,
        "but it reads as a double");

  v = guatiao_map_find(&ROOT, guatiao_cstr("port"));
  CHECK(guatiao_int_or(v, -1) == 5900, "a plain integer reads as one");

  v = guatiao_map_find(&ROOT, guatiao_cstr("nothing"));
  CHECK(guatiao_tag_of(v) == (uint32_t)GUATIAO_NULL, "null is stored");

  v = guatiao_map_find(&ROOT, guatiao_cstr("blob"));
  CHECK(guatiao_bytes_data(v).len == 5, "the NUL did not end it");
  CHECK(memcmp(guatiao_bytes_data(v).ptr, BLOB, sizeof(BLOB)) == 0,
        "every byte survives, 0x00 and 0xff included");

  v = guatiao_map_find(&ROOT, guatiao_cstr("items"));
  CHECK(guatiao_list_items(v).len == 2, "two items");
  CHECK(guatiao_int_or(guatiao_list_at(v, 0), -1) == 1, "first item");
  CHECK(guatiao_int_or(guatiao_list_at(v, 1), -1) == 2, "second item");
  CHECK(guatiao_list_at(v, 2) == NULL, "past the end is NULL, not a fault");

  v = guatiao_map_find(&ROOT, guatiao_cstr("tls"));
  CHECK(guatiao_bool_or(guatiao_map_find(v, guatiao_cstr("verify")), false),
        "a nested map reads");

  CHECK(guatiao_map_find(&ROOT, guatiao_cstr("absent")) == NULL,
        "a missing key is NULL");

  /* Insertion order is the contract, and it is visible here. */
  CHECK(str_is(guatiao_entry_key(&guatiao_map_entries(&ROOT).ptr[0]), "host"),
        "first key");
  CHECK(str_is(guatiao_entry_key(&guatiao_map_entries(&ROOT).ptr[7]), "tls"),
        "last key");
}

/* Every accessor answers for NULL rather than faulting. A null is the
   first thing that arrives when a preceding call failed and its result
   went unchecked; faulting there loses the real error. */
static void null_is_answered_not_dereferenced(void) {
  CHECK(guatiao_tag_of(NULL) == (uint32_t)GUATIAO_ABSENT, "tag of NULL");
  CHECK(guatiao_number_text(NULL).len == 0, "number of NULL");
  CHECK(guatiao_string_text(NULL).len == 0, "string of NULL");
  CHECK(guatiao_bytes_data(NULL).len == 0, "bytes of NULL");
  CHECK(guatiao_list_items(NULL).len == 0, "items of NULL");
  CHECK(guatiao_map_entries(NULL).len == 0, "entries of NULL");
  CHECK(guatiao_map_find(NULL, guatiao_cstr("k")) == NULL, "find in NULL");
  CHECK(guatiao_list_at(NULL, 0) == NULL, "index into NULL");
  CHECK(guatiao_bool_or(NULL, true), "bool of NULL is the fallback");
  CHECK(guatiao_int_or(NULL, 42) == 42, "int of NULL is the fallback");
  CHECK(guatiao_entry_key(NULL).len == 0, "key of NULL");
}

/* A key may contain a NUL, which is exactly why lookup compares bytes.
   strcmp would report these two as the same key. */
static void keys_are_bytes_not_c_strings(void) {
  static guatiao_entry ENTRIES[] = {
      {{(uint8_t *)"ab", 2, 0, NULL}, GUATIAO_VALUE_NUMBER_LIT("1")},
      {{(uint8_t *)"ab\0cd", 5, 0, NULL}, GUATIAO_VALUE_NUMBER_LIT("2")},
  };
  static guatiao_value M = GUATIAO_VALUE_MAP_LIT(ENTRIES);

  CHECK(guatiao_int_or(guatiao_map_find(&M, guatiao_str_from("ab", 2)), -1) == 1,
        "the short key");
  CHECK(guatiao_int_or(guatiao_map_find(&M, guatiao_str_from("ab\0cd", 5)), -1) ==
            2,
        "the key with a NUL in the middle is a different key");
}

/* ---- building and freeing by hand, through our own allocator -------- */

/*
 No Rust is linked here either. The point is that the ownership rules are
 followed from C: a buffer with cap > 0 is ours and is returned to the
 allocator that made it, a buffer with cap == 0 belongs to someone else and
 is never touched.
 */
static void build_and_free_by_hand(void) {
  static guatiao_alloc ALLOC = GUATIAO_ALLOC_MALLOC;

  guatiao_entry *entries;
  char *text;
  guatiao_value root;
  size_t i;

  entries = (guatiao_entry *)ALLOC.alloc(ALLOC.ctx, 2 * sizeof(guatiao_entry),
                                         _Alignof(guatiao_entry));
  CHECK(entries != NULL, "the allocator produced an entry array");
  if (entries == NULL) {
    return;
  }

  /* One owned key with an owned value, and one whose value points at
     static storage: a real tree mixes the two, and freeing must tell them
     apart by `cap` alone. */
  text = (char *)ALLOC.alloc(ALLOC.ctx, 4, 1);
  CHECK(text != NULL, "the allocator produced a text buffer");
  if (text == NULL) {
    ALLOC.free(ALLOC.ctx, entries, 2 * sizeof(guatiao_entry),
               _Alignof(guatiao_entry));
    return;
  }
  memcpy(text, "abcd", 4);

  {
    guatiao_string k0 = {(uint8_t *)"owned", 5, 0, NULL};
    guatiao_string k1 = {(uint8_t *)"static", 6, 0, NULL};
    guatiao_value v0;
    guatiao_value v1 = GUATIAO_VALUE_STRING_LIT("not ours");

    v0.tag = (uint32_t)GUATIAO_STRING;
    v0._pad = 0;
    v0.payload.text.ptr = (uint8_t *)text;
    v0.payload.text.len = 4;
    v0.payload.text.cap = 4; /* ours */
    v0.payload.text.alloc = &ALLOC;

    entries[0].key = k0;
    entries[0].value = v0;
    entries[1].key = k1;
    entries[1].value = v1;
  }

  root.tag = (uint32_t)GUATIAO_MAP;
  root._pad = 0;
  root.payload.map.ptr = entries;
  root.payload.map.len = 2;
  root.payload.map.cap = 2; /* ours */
  root.payload.map.alloc = &ALLOC;

  CHECK(str_is(guatiao_string_text(guatiao_map_find(&root, guatiao_cstr("owned"))),
               "abcd"),
        "the hand-built tree reads like any other");
  CHECK(str_is(
            guatiao_string_text(guatiao_map_find(&root, guatiao_cstr("static"))),
            "not ours"),
        "including the borrowed half");

  /* Free it by walking, honouring `cap`. This is the rule a C consumer has
     to follow, so exercising it here is the point of the test. */
  {
    guatiao_map *m = &root.payload.map;
    for (i = 0; i < m->len; i++) {
      guatiao_entry *e = &m->ptr[i];
      if (e->key.cap > 0 && e->key.alloc != NULL) {
        e->key.alloc->free(e->key.alloc->ctx, e->key.ptr, e->key.cap, 1);
      }
      if (e->value.tag == (uint32_t)GUATIAO_STRING &&
          e->value.payload.text.cap > 0 &&
          e->value.payload.text.alloc != NULL) {
        e->value.payload.text.alloc->free(e->value.payload.text.alloc->ctx,
                                          e->value.payload.text.ptr,
                                          e->value.payload.text.cap, 1);
      }
    }
    if (m->cap > 0 && m->alloc != NULL) {
      m->alloc->free(m->alloc->ctx, m->ptr, m->cap * sizeof(guatiao_entry),
                     _Alignof(guatiao_entry));
    }
  }
}

/* A tag from a producer this build has never heard of must be skippable:
   the value beside it still reads. */
static void an_unknown_tag_does_not_stop_the_rest(void) {
  static guatiao_entry ENTRIES[] = {
      GUATIAO_ENTRY_LIT("known", GUATIAO_VALUE_STRING_LIT("readable")),
      GUATIAO_ENTRY_LIT("future", {4242u, 0, {.b = false}}),
  };
  static guatiao_value M = GUATIAO_VALUE_MAP_LIT(ENTRIES);
  const guatiao_value *unknown = guatiao_map_find(&M, guatiao_cstr("future"));

  CHECK(guatiao_tag_of(unknown) == 4242u, "the raw tag is readable");
  CHECK(guatiao_string_text(unknown).len == 0, "no accessor claims it");
  CHECK(guatiao_number_text(unknown).len == 0, "no accessor claims it");
  CHECK(str_is(guatiao_string_text(guatiao_map_find(&M, guatiao_cstr("known"))),
               "readable"),
        "and every other value still reads");
}

/* The boolean arm is a bool, and reads back as one. */
static void a_bool_reads_back(void) {
  guatiao_value v;
  memset(&v, 0, sizeof(v));
  v.tag = (uint32_t)GUATIAO_BOOL;
  v.payload.b = true;
  CHECK(guatiao_bool_or(&v, false), "true is true");
  v.payload.b = false;
  CHECK(!guatiao_bool_or(&v, true), "and false is false");
}

int main(void) {
  read_the_literal();
  null_is_answered_not_dereferenced();
  keys_are_bytes_not_c_strings();
  build_and_free_by_hand();
  an_unknown_tag_does_not_stop_the_rest();
  a_bool_reads_back();

  if (failures == 0) {
    printf("c_consumer: all checks passed\n");
    return 0;
  }
  printf("c_consumer: %d check(s) failed\n", failures);
  return 1;
}
