// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
//
// GENERATED by ffigen. Do not edit: run `dart run ffigen` instead.

// ignore_for_file: always_specify_types, camel_case_types
// ignore_for_file: non_constant_identifier_names, unused_field

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import, unused_element, deprecated_member_use_from_same_package
import 'dart:ffi' as ffi;

/// Raw dart:ffi bindings over the guatiao C ABI, generated from crates/guatiao/include/guatiao.h and the sibling headers for the serde and form libraries.
class GuatiaoBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  GuatiaoBindings(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  GuatiaoBindings.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  int guatiao_alloc_default(
    ffi.Pointer<guatiao_alloc> out,
  ) {
    return _guatiao_alloc_default(
      out,
    );
  }

  late final _guatiao_alloc_defaultPtr = _lookup<
      ffi.NativeFunction<
          guatiao_status$1 Function(
              ffi.Pointer<guatiao_alloc>)>>('guatiao_alloc_default');
  late final _guatiao_alloc_default = _guatiao_alloc_defaultPtr
      .asFunction<int Function(ffi.Pointer<guatiao_alloc>)>();

  int guatiao_buffer_push(
    ffi.Pointer<guatiao_alloc> alloc,
    ffi.Pointer<guatiao_value> node,
    guatiao_bytes bytes,
  ) {
    return _guatiao_buffer_push(
      alloc,
      node,
      bytes,
    );
  }

  late final _guatiao_buffer_pushPtr = _lookup<
      ffi.NativeFunction<
          guatiao_status$1 Function(
              ffi.Pointer<guatiao_alloc>,
              ffi.Pointer<guatiao_value>,
              guatiao_bytes)>>('guatiao_buffer_push');
  late final _guatiao_buffer_push = _guatiao_buffer_pushPtr.asFunction<
      int Function(ffi.Pointer<guatiao_alloc>, ffi.Pointer<guatiao_value>,
          guatiao_bytes)>();

  int guatiao_form_check(
    ffi.Pointer<guatiao_value> schema,
    ffi.Pointer<guatiao_value> form,
    ffi.Pointer<guatiao_alloc> alloc,
    ffi.Pointer<guatiao_value> out_error,
  ) {
    return _guatiao_form_check(
      schema,
      form,
      alloc,
      out_error,
    );
  }

  late final _guatiao_form_checkPtr = _lookup<
      ffi.NativeFunction<
          guatiao_status$1 Function(
              ffi.Pointer<guatiao_value>,
              ffi.Pointer<guatiao_value>,
              ffi.Pointer<guatiao_alloc>,
              ffi.Pointer<guatiao_value>)>>('guatiao_form_check');
  late final _guatiao_form_check = _guatiao_form_checkPtr.asFunction<
      int Function(ffi.Pointer<guatiao_value>, ffi.Pointer<guatiao_value>,
          ffi.Pointer<guatiao_alloc>, ffi.Pointer<guatiao_value>)>();

  int guatiao_form_is_visible(
    ffi.Pointer<guatiao_value> schema,
    ffi.Pointer<guatiao_value> form,
    guatiao_str key,
    ffi.Pointer<guatiao_value> values,
    ffi.Pointer<ffi.Bool> out,
  ) {
    return _guatiao_form_is_visible(
      schema,
      form,
      key,
      values,
      out,
    );
  }

  late final _guatiao_form_is_visiblePtr = _lookup<
      ffi.NativeFunction<
          guatiao_status$1 Function(
              ffi.Pointer<guatiao_value>,
              ffi.Pointer<guatiao_value>,
              guatiao_str,
              ffi.Pointer<guatiao_value>,
              ffi.Pointer<ffi.Bool>)>>('guatiao_form_is_visible');
  late final _guatiao_form_is_visible = _guatiao_form_is_visiblePtr.asFunction<
      int Function(ffi.Pointer<guatiao_value>, ffi.Pointer<guatiao_value>,
          guatiao_str, ffi.Pointer<guatiao_value>, ffi.Pointer<ffi.Bool>)>();

  int guatiao_form_layout(
    ffi.Pointer<guatiao_value> schema,
    ffi.Pointer<guatiao_value> form,
    ffi.Pointer<guatiao_alloc> alloc,
    ffi.Pointer<guatiao_value> out,
  ) {
    return _guatiao_form_layout(
      schema,
      form,
      alloc,
      out,
    );
  }

  late final _guatiao_form_layoutPtr = _lookup<
      ffi.NativeFunction<
          guatiao_status$1 Function(
              ffi.Pointer<guatiao_value>,
              ffi.Pointer<guatiao_value>,
              ffi.Pointer<guatiao_alloc>,
              ffi.Pointer<guatiao_value>)>>('guatiao_form_layout');
  late final _guatiao_form_layout = _guatiao_form_layoutPtr.asFunction<
      int Function(ffi.Pointer<guatiao_value>, ffi.Pointer<guatiao_value>,
          ffi.Pointer<guatiao_alloc>, ffi.Pointer<guatiao_value>)>();

  int guatiao_json_emit(
    ffi.Pointer<guatiao_value> value,
    int how,
    ffi.Pointer<guatiao_alloc> alloc,
    ffi.Pointer<guatiao_value> out,
  ) {
    return _guatiao_json_emit(
      value,
      how,
      alloc,
      out,
    );
  }

  late final _guatiao_json_emitPtr = _lookup<
      ffi.NativeFunction<
          guatiao_status$1 Function(
              ffi.Pointer<guatiao_value>,
              ffi.Uint32,
              ffi.Pointer<guatiao_alloc>,
              ffi.Pointer<guatiao_value>)>>('guatiao_json_emit');
  late final _guatiao_json_emit = _guatiao_json_emitPtr.asFunction<
      int Function(ffi.Pointer<guatiao_value>, int, ffi.Pointer<guatiao_alloc>,
          ffi.Pointer<guatiao_value>)>();

  int guatiao_json_emit_pretty(
    ffi.Pointer<guatiao_value> value,
    int how,
    ffi.Pointer<guatiao_alloc> alloc,
    ffi.Pointer<guatiao_value> out,
  ) {
    return _guatiao_json_emit_pretty(
      value,
      how,
      alloc,
      out,
    );
  }

  late final _guatiao_json_emit_prettyPtr = _lookup<
      ffi.NativeFunction<
          guatiao_status$1 Function(
              ffi.Pointer<guatiao_value>,
              ffi.Uint32,
              ffi.Pointer<guatiao_alloc>,
              ffi.Pointer<guatiao_value>)>>('guatiao_json_emit_pretty');
  late final _guatiao_json_emit_pretty =
      _guatiao_json_emit_prettyPtr.asFunction<
          int Function(ffi.Pointer<guatiao_value>, int,
              ffi.Pointer<guatiao_alloc>, ffi.Pointer<guatiao_value>)>();

  int guatiao_json_parse(
    guatiao_str text,
    int how,
    ffi.Pointer<guatiao_alloc> alloc,
    ffi.Pointer<guatiao_value> out,
  ) {
    return _guatiao_json_parse(
      text,
      how,
      alloc,
      out,
    );
  }

  late final _guatiao_json_parsePtr = _lookup<
      ffi.NativeFunction<
          guatiao_status$1 Function(
              guatiao_str,
              ffi.Uint32,
              ffi.Pointer<guatiao_alloc>,
              ffi.Pointer<guatiao_value>)>>('guatiao_json_parse');
  late final _guatiao_json_parse = _guatiao_json_parsePtr.asFunction<
      int Function(guatiao_str, int, ffi.Pointer<guatiao_alloc>,
          ffi.Pointer<guatiao_value>)>();

  int guatiao_list_clear(
    ffi.Pointer<guatiao_value> node,
  ) {
    return _guatiao_list_clear(
      node,
    );
  }

  late final _guatiao_list_clearPtr = _lookup<
      ffi.NativeFunction<
          guatiao_status$1 Function(
              ffi.Pointer<guatiao_value>)>>('guatiao_list_clear');
  late final _guatiao_list_clear = _guatiao_list_clearPtr
      .asFunction<int Function(ffi.Pointer<guatiao_value>)>();

  int guatiao_list_discard(
    ffi.Pointer<guatiao_value> node,
    int index,
  ) {
    return _guatiao_list_discard(
      node,
      index,
    );
  }

  late final _guatiao_list_discardPtr = _lookup<
      ffi.NativeFunction<
          guatiao_status$1 Function(
              ffi.Pointer<guatiao_value>, ffi.Size)>>('guatiao_list_discard');
  late final _guatiao_list_discard = _guatiao_list_discardPtr
      .asFunction<int Function(ffi.Pointer<guatiao_value>, int)>();

  int guatiao_list_push(
    ffi.Pointer<guatiao_alloc> alloc,
    ffi.Pointer<guatiao_value> node,
    ffi.Pointer<guatiao_value> value,
  ) {
    return _guatiao_list_push(
      alloc,
      node,
      value,
    );
  }

  late final _guatiao_list_pushPtr = _lookup<
      ffi.NativeFunction<
          guatiao_status$1 Function(
              ffi.Pointer<guatiao_alloc>,
              ffi.Pointer<guatiao_value>,
              ffi.Pointer<guatiao_value>)>>('guatiao_list_push');
  late final _guatiao_list_push = _guatiao_list_pushPtr.asFunction<
      int Function(ffi.Pointer<guatiao_alloc>, ffi.Pointer<guatiao_value>,
          ffi.Pointer<guatiao_value>)>();

  int guatiao_map_clear(
    ffi.Pointer<guatiao_value> node,
  ) {
    return _guatiao_map_clear(
      node,
    );
  }

  late final _guatiao_map_clearPtr = _lookup<
      ffi.NativeFunction<
          guatiao_status$1 Function(
              ffi.Pointer<guatiao_value>)>>('guatiao_map_clear');
  late final _guatiao_map_clear = _guatiao_map_clearPtr
      .asFunction<int Function(ffi.Pointer<guatiao_value>)>();

  int guatiao_map_copy_from(
    ffi.Pointer<guatiao_alloc> alloc,
    ffi.Pointer<guatiao_value> dst,
    ffi.Pointer<guatiao_value> src,
  ) {
    return _guatiao_map_copy_from(
      alloc,
      dst,
      src,
    );
  }

  late final _guatiao_map_copy_fromPtr = _lookup<
      ffi.NativeFunction<
          guatiao_status$1 Function(
              ffi.Pointer<guatiao_alloc>,
              ffi.Pointer<guatiao_value>,
              ffi.Pointer<guatiao_value>)>>('guatiao_map_copy_from');
  late final _guatiao_map_copy_from = _guatiao_map_copy_fromPtr.asFunction<
      int Function(ffi.Pointer<guatiao_alloc>, ffi.Pointer<guatiao_value>,
          ffi.Pointer<guatiao_value>)>();

  int guatiao_map_discard(
    ffi.Pointer<guatiao_value> node,
    guatiao_str key,
  ) {
    return _guatiao_map_discard(
      node,
      key,
    );
  }

  late final _guatiao_map_discardPtr = _lookup<
      ffi.NativeFunction<
          guatiao_status$1 Function(
              ffi.Pointer<guatiao_value>, guatiao_str)>>('guatiao_map_discard');
  late final _guatiao_map_discard = _guatiao_map_discardPtr
      .asFunction<int Function(ffi.Pointer<guatiao_value>, guatiao_str)>();

  int guatiao_map_set(
    ffi.Pointer<guatiao_alloc> alloc,
    ffi.Pointer<guatiao_value> node,
    guatiao_str key,
    ffi.Pointer<guatiao_value> value,
  ) {
    return _guatiao_map_set(
      alloc,
      node,
      key,
      value,
    );
  }

  late final _guatiao_map_setPtr = _lookup<
      ffi.NativeFunction<
          guatiao_status$1 Function(
              ffi.Pointer<guatiao_alloc>,
              ffi.Pointer<guatiao_value>,
              guatiao_str,
              ffi.Pointer<guatiao_value>)>>('guatiao_map_set');
  late final _guatiao_map_set = _guatiao_map_setPtr.asFunction<
      int Function(ffi.Pointer<guatiao_alloc>, ffi.Pointer<guatiao_value>,
          guatiao_str, ffi.Pointer<guatiao_value>)>();

  int guatiao_merge(
    int mode,
    ffi.Pointer<guatiao_value> earlier,
    ffi.Pointer<guatiao_value> later,
    ffi.Pointer<guatiao_alloc> alloc,
    int options,
    ffi.Pointer<guatiao_merge_override> overrides,
    int overrides_len,
    ffi.Pointer<guatiao_value> out,
    ffi.Pointer<guatiao_value> out_error,
  ) {
    return _guatiao_merge(
      mode,
      earlier,
      later,
      alloc,
      options,
      overrides,
      overrides_len,
      out,
      out_error,
    );
  }

  late final _guatiao_mergePtr = _lookup<
      ffi.NativeFunction<
          guatiao_status$1 Function(
              ffi.Uint32,
              ffi.Pointer<guatiao_value>,
              ffi.Pointer<guatiao_value>,
              ffi.Pointer<guatiao_alloc>,
              ffi.Uint32,
              ffi.Pointer<guatiao_merge_override>,
              ffi.Size,
              ffi.Pointer<guatiao_value>,
              ffi.Pointer<guatiao_value>)>>('guatiao_merge');
  late final _guatiao_merge = _guatiao_mergePtr.asFunction<
      int Function(
          int,
          ffi.Pointer<guatiao_value>,
          ffi.Pointer<guatiao_value>,
          ffi.Pointer<guatiao_alloc>,
          int,
          ffi.Pointer<guatiao_merge_override>,
          int,
          ffi.Pointer<guatiao_value>,
          ffi.Pointer<guatiao_value>)>();

  int guatiao_registry_available(
    ffi.Pointer<guatiao_registry> reg,
    guatiao_str kind,
    ffi.Pointer<guatiao_alloc> alloc,
    ffi.Pointer<guatiao_value> out,
  ) {
    return _guatiao_registry_available(
      reg,
      kind,
      alloc,
      out,
    );
  }

  late final _guatiao_registry_availablePtr = _lookup<
      ffi.NativeFunction<
          guatiao_status$1 Function(
              ffi.Pointer<guatiao_registry>,
              guatiao_str,
              ffi.Pointer<guatiao_alloc>,
              ffi.Pointer<guatiao_value>)>>('guatiao_registry_available');
  late final _guatiao_registry_available =
      _guatiao_registry_availablePtr.asFunction<
          int Function(ffi.Pointer<guatiao_registry>, guatiao_str,
              ffi.Pointer<guatiao_alloc>, ffi.Pointer<guatiao_value>)>();

  int guatiao_registry_best(
    ffi.Pointer<guatiao_registry> reg,
    guatiao_str kind,
    ffi.Pointer<guatiao_alloc> alloc,
    ffi.Pointer<guatiao_value> out,
  ) {
    return _guatiao_registry_best(
      reg,
      kind,
      alloc,
      out,
    );
  }

  late final _guatiao_registry_bestPtr = _lookup<
      ffi.NativeFunction<
          guatiao_status$1 Function(
              ffi.Pointer<guatiao_registry>,
              guatiao_str,
              ffi.Pointer<guatiao_alloc>,
              ffi.Pointer<guatiao_value>)>>('guatiao_registry_best');
  late final _guatiao_registry_best = _guatiao_registry_bestPtr.asFunction<
      int Function(ffi.Pointer<guatiao_registry>, guatiao_str,
          ffi.Pointer<guatiao_alloc>, ffi.Pointer<guatiao_value>)>();

  void guatiao_registry_free(
    ffi.Pointer<guatiao_registry> reg,
  ) {
    return _guatiao_registry_free(
      reg,
    );
  }

  late final _guatiao_registry_freePtr = _lookup<
          ffi.NativeFunction<ffi.Void Function(ffi.Pointer<guatiao_registry>)>>(
      'guatiao_registry_free');
  late final _guatiao_registry_free = _guatiao_registry_freePtr
      .asFunction<void Function(ffi.Pointer<guatiao_registry>)>();

  ffi.Pointer<guatiao_host_info> guatiao_registry_host(
    ffi.Pointer<guatiao_registry> reg,
  ) {
    return _guatiao_registry_host(
      reg,
    );
  }

  late final _guatiao_registry_hostPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<guatiao_host_info> Function(
              ffi.Pointer<guatiao_registry>)>>('guatiao_registry_host');
  late final _guatiao_registry_host = _guatiao_registry_hostPtr.asFunction<
      ffi.Pointer<guatiao_host_info> Function(ffi.Pointer<guatiao_registry>)>();

  int guatiao_registry_keyed_by(
    ffi.Pointer<guatiao_registry> reg,
    guatiao_str template_,
  ) {
    return _guatiao_registry_keyed_by(
      reg,
      template_,
    );
  }

  late final _guatiao_registry_keyed_byPtr = _lookup<
      ffi.NativeFunction<
          guatiao_status$1 Function(ffi.Pointer<guatiao_registry>,
              guatiao_str)>>('guatiao_registry_keyed_by');
  late final _guatiao_registry_keyed_by = _guatiao_registry_keyed_byPtr
      .asFunction<int Function(ffi.Pointer<guatiao_registry>, guatiao_str)>();

  int guatiao_registry_libraries(
    ffi.Pointer<guatiao_registry> reg,
    ffi.Pointer<guatiao_alloc> alloc,
    ffi.Pointer<guatiao_value> out,
  ) {
    return _guatiao_registry_libraries(
      reg,
      alloc,
      out,
    );
  }

  late final _guatiao_registry_librariesPtr = _lookup<
      ffi.NativeFunction<
          guatiao_status$1 Function(
              ffi.Pointer<guatiao_registry>,
              ffi.Pointer<guatiao_alloc>,
              ffi.Pointer<guatiao_value>)>>('guatiao_registry_libraries');
  late final _guatiao_registry_libraries =
      _guatiao_registry_librariesPtr.asFunction<
          int Function(ffi.Pointer<guatiao_registry>,
              ffi.Pointer<guatiao_alloc>, ffi.Pointer<guatiao_value>)>();

  int guatiao_registry_libraries_keyed_by(
    ffi.Pointer<guatiao_registry> reg,
    guatiao_str template_,
  ) {
    return _guatiao_registry_libraries_keyed_by(
      reg,
      template_,
    );
  }

  late final _guatiao_registry_libraries_keyed_byPtr = _lookup<
      ffi.NativeFunction<
          guatiao_status$1 Function(ffi.Pointer<guatiao_registry>,
              guatiao_str)>>('guatiao_registry_libraries_keyed_by');
  late final _guatiao_registry_libraries_keyed_by =
      _guatiao_registry_libraries_keyed_byPtr.asFunction<
          int Function(ffi.Pointer<guatiao_registry>, guatiao_str)>();

  int guatiao_registry_load_file(
    ffi.Pointer<guatiao_registry> reg,
    guatiao_str path,
    ffi.Pointer<guatiao_alloc> alloc,
    ffi.Pointer<guatiao_value> out,
  ) {
    return _guatiao_registry_load_file(
      reg,
      path,
      alloc,
      out,
    );
  }

  late final _guatiao_registry_load_filePtr = _lookup<
      ffi.NativeFunction<
          guatiao_status$1 Function(
              ffi.Pointer<guatiao_registry>,
              guatiao_str,
              ffi.Pointer<guatiao_alloc>,
              ffi.Pointer<guatiao_value>)>>('guatiao_registry_load_file');
  late final _guatiao_registry_load_file =
      _guatiao_registry_load_filePtr.asFunction<
          int Function(ffi.Pointer<guatiao_registry>, guatiao_str,
              ffi.Pointer<guatiao_alloc>, ffi.Pointer<guatiao_value>)>();

  ffi.Pointer<guatiao_registry> guatiao_registry_new(
    guatiao_str id,
    guatiao_str version,
    ffi.Pointer<guatiao_alloc> alloc,
  ) {
    return _guatiao_registry_new(
      id,
      version,
      alloc,
    );
  }

  late final _guatiao_registry_newPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<guatiao_registry> Function(guatiao_str, guatiao_str,
              ffi.Pointer<guatiao_alloc>)>>('guatiao_registry_new');
  late final _guatiao_registry_new = _guatiao_registry_newPtr.asFunction<
      ffi.Pointer<guatiao_registry> Function(
          guatiao_str, guatiao_str, ffi.Pointer<guatiao_alloc>)>();

  int guatiao_registry_priority(
    ffi.Pointer<guatiao_registry> reg,
    guatiao_str id,
  ) {
    return _guatiao_registry_priority(
      reg,
      id,
    );
  }

  late final _guatiao_registry_priorityPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<guatiao_registry>,
              guatiao_str)>>('guatiao_registry_priority');
  late final _guatiao_registry_priority = _guatiao_registry_priorityPtr
      .asFunction<int Function(ffi.Pointer<guatiao_registry>, guatiao_str)>();

  int guatiao_registry_provider(
    ffi.Pointer<guatiao_registry> reg,
    guatiao_str key,
    ffi.Pointer<guatiao_alloc> alloc,
    ffi.Pointer<guatiao_value> out,
  ) {
    return _guatiao_registry_provider(
      reg,
      key,
      alloc,
      out,
    );
  }

  late final _guatiao_registry_providerPtr = _lookup<
      ffi.NativeFunction<
          guatiao_status$1 Function(
              ffi.Pointer<guatiao_registry>,
              guatiao_str,
              ffi.Pointer<guatiao_alloc>,
              ffi.Pointer<guatiao_value>)>>('guatiao_registry_provider');
  late final _guatiao_registry_provider =
      _guatiao_registry_providerPtr.asFunction<
          int Function(ffi.Pointer<guatiao_registry>, guatiao_str,
              ffi.Pointer<guatiao_alloc>, ffi.Pointer<guatiao_value>)>();

  bool guatiao_registry_provider_available(
    ffi.Pointer<guatiao_registry> reg,
    guatiao_str key,
    ffi.Pointer<guatiao_str> reason,
  ) {
    return _guatiao_registry_provider_available(
      reg,
      key,
      reason,
    );
  }

  late final _guatiao_registry_provider_availablePtr = _lookup<
          ffi.NativeFunction<
              ffi.Bool Function(ffi.Pointer<guatiao_registry>, guatiao_str,
                  ffi.Pointer<guatiao_str>)>>(
      'guatiao_registry_provider_available');
  late final _guatiao_registry_provider_available =
      _guatiao_registry_provider_availablePtr.asFunction<
          bool Function(ffi.Pointer<guatiao_registry>, guatiao_str,
              ffi.Pointer<guatiao_str>)>();

  ffi.Pointer<guatiao_value> guatiao_registry_provider_config(
    ffi.Pointer<guatiao_registry> reg,
    guatiao_str key,
  ) {
    return _guatiao_registry_provider_config(
      reg,
      key,
    );
  }

  late final _guatiao_registry_provider_configPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<guatiao_value> Function(ffi.Pointer<guatiao_registry>,
              guatiao_str)>>('guatiao_registry_provider_config');
  late final _guatiao_registry_provider_config =
      _guatiao_registry_provider_configPtr.asFunction<
          ffi.Pointer<guatiao_value> Function(
              ffi.Pointer<guatiao_registry>, guatiao_str)>();

  int guatiao_registry_provider_create(
    ffi.Pointer<guatiao_registry> reg,
    guatiao_str key,
    ffi.Pointer<guatiao_value> config,
    ffi.Pointer<ffi.Pointer<ffi.Void>> out,
    ffi.Pointer<guatiao_provider_error> err,
  ) {
    return _guatiao_registry_provider_create(
      reg,
      key,
      config,
      out,
      err,
    );
  }

  late final _guatiao_registry_provider_createPtr = _lookup<
          ffi.NativeFunction<
              guatiao_status$1 Function(
                  ffi.Pointer<guatiao_registry>,
                  guatiao_str,
                  ffi.Pointer<guatiao_value>,
                  ffi.Pointer<ffi.Pointer<ffi.Void>>,
                  ffi.Pointer<guatiao_provider_error>)>>(
      'guatiao_registry_provider_create');
  late final _guatiao_registry_provider_create =
      _guatiao_registry_provider_createPtr.asFunction<
          int Function(
              ffi.Pointer<guatiao_registry>,
              guatiao_str,
              ffi.Pointer<guatiao_value>,
              ffi.Pointer<ffi.Pointer<ffi.Void>>,
              ffi.Pointer<guatiao_provider_error>)>();

  ffi.Pointer<ffi.Void> guatiao_registry_provider_ctx(
    ffi.Pointer<guatiao_registry> reg,
    guatiao_str key,
  ) {
    return _guatiao_registry_provider_ctx(
      reg,
      key,
    );
  }

  late final _guatiao_registry_provider_ctxPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Void> Function(ffi.Pointer<guatiao_registry>,
              guatiao_str)>>('guatiao_registry_provider_ctx');
  late final _guatiao_registry_provider_ctx =
      _guatiao_registry_provider_ctxPtr.asFunction<
          ffi.Pointer<ffi.Void> Function(
              ffi.Pointer<guatiao_registry>, guatiao_str)>();

  void guatiao_registry_provider_destroy(
    ffi.Pointer<guatiao_registry> reg,
    guatiao_str key,
    ffi.Pointer<ffi.Void> instance,
  ) {
    return _guatiao_registry_provider_destroy(
      reg,
      key,
      instance,
    );
  }

  late final _guatiao_registry_provider_destroyPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<guatiao_registry>, guatiao_str,
              ffi.Pointer<ffi.Void>)>>('guatiao_registry_provider_destroy');
  late final _guatiao_registry_provider_destroy =
      _guatiao_registry_provider_destroyPtr.asFunction<
          void Function(ffi.Pointer<guatiao_registry>, guatiao_str,
              ffi.Pointer<ffi.Void>)>();

  ffi.Pointer<ffi.Void> guatiao_registry_provider_table(
    ffi.Pointer<guatiao_registry> reg,
    guatiao_str key,
    guatiao_str kind,
    ffi.Pointer<ffi.Size> size_out,
  ) {
    return _guatiao_registry_provider_table(
      reg,
      key,
      kind,
      size_out,
    );
  }

  late final _guatiao_registry_provider_tablePtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Void> Function(
              ffi.Pointer<guatiao_registry>,
              guatiao_str,
              guatiao_str,
              ffi.Pointer<ffi.Size>)>>('guatiao_registry_provider_table');
  late final _guatiao_registry_provider_table =
      _guatiao_registry_provider_tablePtr.asFunction<
          ffi.Pointer<ffi.Void> Function(ffi.Pointer<guatiao_registry>,
              guatiao_str, guatiao_str, ffi.Pointer<ffi.Size>)>();

  ffi.Pointer<ffi.Void> guatiao_registry_provider_vtable(
    ffi.Pointer<guatiao_registry> reg,
    guatiao_str key,
    ffi.Pointer<ffi.Size> size_out,
  ) {
    return _guatiao_registry_provider_vtable(
      reg,
      key,
      size_out,
    );
  }

  late final _guatiao_registry_provider_vtablePtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Void> Function(
              ffi.Pointer<guatiao_registry>,
              guatiao_str,
              ffi.Pointer<ffi.Size>)>>('guatiao_registry_provider_vtable');
  late final _guatiao_registry_provider_vtable =
      _guatiao_registry_provider_vtablePtr.asFunction<
          ffi.Pointer<ffi.Void> Function(ffi.Pointer<guatiao_registry>,
              guatiao_str, ffi.Pointer<ffi.Size>)>();

  int guatiao_registry_providers(
    ffi.Pointer<guatiao_registry> reg,
    guatiao_str kind,
    ffi.Pointer<guatiao_alloc> alloc,
    ffi.Pointer<guatiao_value> out,
  ) {
    return _guatiao_registry_providers(
      reg,
      kind,
      alloc,
      out,
    );
  }

  late final _guatiao_registry_providersPtr = _lookup<
      ffi.NativeFunction<
          guatiao_status$1 Function(
              ffi.Pointer<guatiao_registry>,
              guatiao_str,
              ffi.Pointer<guatiao_alloc>,
              ffi.Pointer<guatiao_value>)>>('guatiao_registry_providers');
  late final _guatiao_registry_providers =
      _guatiao_registry_providersPtr.asFunction<
          int Function(ffi.Pointer<guatiao_registry>, guatiao_str,
              ffi.Pointer<guatiao_alloc>, ffi.Pointer<guatiao_value>)>();

  int guatiao_registry_register_entry(
    ffi.Pointer<guatiao_registry> reg,
    guatiao_str name,
    ffi.Pointer<
            ffi.NativeFunction<
                ffi.Pointer<guatiao_library_info> Function(
                    ffi.Pointer<guatiao_host_info>)>>
        entry,
    ffi.Pointer<guatiao_alloc> alloc,
    ffi.Pointer<guatiao_value> out,
  ) {
    return _guatiao_registry_register_entry(
      reg,
      name,
      entry,
      alloc,
      out,
    );
  }

  late final _guatiao_registry_register_entryPtr = _lookup<
      ffi.NativeFunction<
          guatiao_status$1 Function(
              ffi.Pointer<guatiao_registry>,
              guatiao_str,
              ffi.Pointer<
                  ffi.NativeFunction<
                      ffi.Pointer<guatiao_library_info> Function(
                          ffi.Pointer<guatiao_host_info>)>>,
              ffi.Pointer<guatiao_alloc>,
              ffi.Pointer<guatiao_value>)>>('guatiao_registry_register_entry');
  late final _guatiao_registry_register_entry =
      _guatiao_registry_register_entryPtr.asFunction<
          int Function(
              ffi.Pointer<guatiao_registry>,
              guatiao_str,
              ffi.Pointer<
                  ffi.NativeFunction<
                      ffi.Pointer<guatiao_library_info> Function(
                          ffi.Pointer<guatiao_host_info>)>>,
              ffi.Pointer<guatiao_alloc>,
              ffi.Pointer<guatiao_value>)>();

  int guatiao_registry_retire(
    ffi.Pointer<guatiao_registry> reg,
    guatiao_str key,
  ) {
    return _guatiao_registry_retire(
      reg,
      key,
    );
  }

  late final _guatiao_registry_retirePtr = _lookup<
      ffi.NativeFunction<
          guatiao_status$1 Function(ffi.Pointer<guatiao_registry>,
              guatiao_str)>>('guatiao_registry_retire');
  late final _guatiao_registry_retire = _guatiao_registry_retirePtr
      .asFunction<int Function(ffi.Pointer<guatiao_registry>, guatiao_str)>();

  int guatiao_registry_scan_dir(
    ffi.Pointer<guatiao_registry> reg,
    guatiao_str dir,
    bool descending,
    ffi.Pointer<guatiao_alloc> alloc,
    ffi.Pointer<guatiao_value> out,
  ) {
    return _guatiao_registry_scan_dir(
      reg,
      dir,
      descending,
      alloc,
      out,
    );
  }

  late final _guatiao_registry_scan_dirPtr = _lookup<
      ffi.NativeFunction<
          guatiao_status$1 Function(
              ffi.Pointer<guatiao_registry>,
              guatiao_str,
              ffi.Bool,
              ffi.Pointer<guatiao_alloc>,
              ffi.Pointer<guatiao_value>)>>('guatiao_registry_scan_dir');
  late final _guatiao_registry_scan_dir =
      _guatiao_registry_scan_dirPtr.asFunction<
          int Function(ffi.Pointer<guatiao_registry>, guatiao_str, bool,
              ffi.Pointer<guatiao_alloc>, ffi.Pointer<guatiao_value>)>();

  int guatiao_registry_scan_dir_rules(
    ffi.Pointer<guatiao_registry> reg,
    guatiao_str dir,
    bool descending,
    guatiao_str rules,
    ffi.Pointer<guatiao_alloc> alloc,
    ffi.Pointer<guatiao_value> out,
  ) {
    return _guatiao_registry_scan_dir_rules(
      reg,
      dir,
      descending,
      rules,
      alloc,
      out,
    );
  }

  late final _guatiao_registry_scan_dir_rulesPtr = _lookup<
      ffi.NativeFunction<
          guatiao_status$1 Function(
              ffi.Pointer<guatiao_registry>,
              guatiao_str,
              ffi.Bool,
              guatiao_str,
              ffi.Pointer<guatiao_alloc>,
              ffi.Pointer<guatiao_value>)>>('guatiao_registry_scan_dir_rules');
  late final _guatiao_registry_scan_dir_rules =
      _guatiao_registry_scan_dir_rulesPtr.asFunction<
          int Function(
              ffi.Pointer<guatiao_registry>,
              guatiao_str,
              bool,
              guatiao_str,
              ffi.Pointer<guatiao_alloc>,
              ffi.Pointer<guatiao_value>)>();

  int guatiao_registry_scan_path(
    ffi.Pointer<guatiao_registry> reg,
    guatiao_str spec,
    bool descending,
    guatiao_str rules,
    ffi.Pointer<guatiao_alloc> alloc,
    ffi.Pointer<guatiao_value> out,
  ) {
    return _guatiao_registry_scan_path(
      reg,
      spec,
      descending,
      rules,
      alloc,
      out,
    );
  }

  late final _guatiao_registry_scan_pathPtr = _lookup<
      ffi.NativeFunction<
          guatiao_status$1 Function(
              ffi.Pointer<guatiao_registry>,
              guatiao_str,
              ffi.Bool,
              guatiao_str,
              ffi.Pointer<guatiao_alloc>,
              ffi.Pointer<guatiao_value>)>>('guatiao_registry_scan_path');
  late final _guatiao_registry_scan_path =
      _guatiao_registry_scan_pathPtr.asFunction<
          int Function(
              ffi.Pointer<guatiao_registry>,
              guatiao_str,
              bool,
              guatiao_str,
              ffi.Pointer<guatiao_alloc>,
              ffi.Pointer<guatiao_value>)>();

  int guatiao_registry_set_priority(
    ffi.Pointer<guatiao_registry> reg,
    guatiao_str id,
    int priority,
  ) {
    return _guatiao_registry_set_priority(
      reg,
      id,
      priority,
    );
  }

  late final _guatiao_registry_set_priorityPtr = _lookup<
      ffi.NativeFunction<
          guatiao_status$1 Function(ffi.Pointer<guatiao_registry>, guatiao_str,
              ffi.Int32)>>('guatiao_registry_set_priority');
  late final _guatiao_registry_set_priority =
      _guatiao_registry_set_priorityPtr.asFunction<
          int Function(ffi.Pointer<guatiao_registry>, guatiao_str, int)>();

  int guatiao_registry_unload(
    ffi.Pointer<guatiao_registry> reg,
    guatiao_str key,
  ) {
    return _guatiao_registry_unload(
      reg,
      key,
    );
  }

  late final _guatiao_registry_unloadPtr = _lookup<
      ffi.NativeFunction<
          guatiao_status$1 Function(ffi.Pointer<guatiao_registry>,
              guatiao_str)>>('guatiao_registry_unload');
  late final _guatiao_registry_unload = _guatiao_registry_unloadPtr
      .asFunction<int Function(ffi.Pointer<guatiao_registry>, guatiao_str)>();

  int guatiao_registry_unload_unchecked(
    ffi.Pointer<guatiao_registry> reg,
    guatiao_str key,
  ) {
    return _guatiao_registry_unload_unchecked(
      reg,
      key,
    );
  }

  late final _guatiao_registry_unload_uncheckedPtr = _lookup<
      ffi.NativeFunction<
          guatiao_status$1 Function(ffi.Pointer<guatiao_registry>,
              guatiao_str)>>('guatiao_registry_unload_unchecked');
  late final _guatiao_registry_unload_unchecked =
      _guatiao_registry_unload_uncheckedPtr.asFunction<
          int Function(ffi.Pointer<guatiao_registry>, guatiao_str)>();

  int guatiao_registry_why_not(
    ffi.Pointer<guatiao_registry> reg,
    guatiao_str kind,
    ffi.Pointer<guatiao_alloc> alloc,
    ffi.Pointer<guatiao_value> out,
  ) {
    return _guatiao_registry_why_not(
      reg,
      kind,
      alloc,
      out,
    );
  }

  late final _guatiao_registry_why_notPtr = _lookup<
      ffi.NativeFunction<
          guatiao_status$1 Function(
              ffi.Pointer<guatiao_registry>,
              guatiao_str,
              ffi.Pointer<guatiao_alloc>,
              ffi.Pointer<guatiao_value>)>>('guatiao_registry_why_not');
  late final _guatiao_registry_why_not =
      _guatiao_registry_why_notPtr.asFunction<
          int Function(ffi.Pointer<guatiao_registry>, guatiao_str,
              ffi.Pointer<guatiao_alloc>, ffi.Pointer<guatiao_value>)>();

  int guatiao_schema_flat_keys(
    ffi.Pointer<guatiao_value> schema,
    guatiao_str key,
    ffi.Pointer<guatiao_alloc> alloc,
    ffi.Pointer<guatiao_value> out,
  ) {
    return _guatiao_schema_flat_keys(
      schema,
      key,
      alloc,
      out,
    );
  }

  late final _guatiao_schema_flat_keysPtr = _lookup<
      ffi.NativeFunction<
          guatiao_status$1 Function(
              ffi.Pointer<guatiao_value>,
              guatiao_str,
              ffi.Pointer<guatiao_alloc>,
              ffi.Pointer<guatiao_value>)>>('guatiao_schema_flat_keys');
  late final _guatiao_schema_flat_keys =
      _guatiao_schema_flat_keysPtr.asFunction<
          int Function(ffi.Pointer<guatiao_value>, guatiao_str,
              ffi.Pointer<guatiao_alloc>, ffi.Pointer<guatiao_value>)>();

  int guatiao_schema_flatten(
    ffi.Pointer<guatiao_value> schema,
    guatiao_str key,
    ffi.Pointer<guatiao_value> value,
    ffi.Pointer<guatiao_alloc> alloc,
    ffi.Pointer<guatiao_value> out,
  ) {
    return _guatiao_schema_flatten(
      schema,
      key,
      value,
      alloc,
      out,
    );
  }

  late final _guatiao_schema_flattenPtr = _lookup<
      ffi.NativeFunction<
          guatiao_status$1 Function(
              ffi.Pointer<guatiao_value>,
              guatiao_str,
              ffi.Pointer<guatiao_value>,
              ffi.Pointer<guatiao_alloc>,
              ffi.Pointer<guatiao_value>)>>('guatiao_schema_flatten');
  late final _guatiao_schema_flatten = _guatiao_schema_flattenPtr.asFunction<
      int Function(
          ffi.Pointer<guatiao_value>,
          guatiao_str,
          ffi.Pointer<guatiao_value>,
          ffi.Pointer<guatiao_alloc>,
          ffi.Pointer<guatiao_value>)>();

  ffi.Pointer<guatiao_value> guatiao_schema_resolve(
    ffi.Pointer<guatiao_value> schema,
    guatiao_str key,
  ) {
    return _guatiao_schema_resolve(
      schema,
      key,
    );
  }

  late final _guatiao_schema_resolvePtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<guatiao_value> Function(ffi.Pointer<guatiao_value>,
              guatiao_str)>>('guatiao_schema_resolve');
  late final _guatiao_schema_resolve = _guatiao_schema_resolvePtr.asFunction<
      ffi.Pointer<guatiao_value> Function(
          ffi.Pointer<guatiao_value>, guatiao_str)>();

  int guatiao_schema_unflatten(
    ffi.Pointer<guatiao_value> schema,
    guatiao_str key,
    ffi.Pointer<guatiao_value> flat,
    ffi.Pointer<guatiao_alloc> alloc,
    ffi.Pointer<guatiao_value> out,
  ) {
    return _guatiao_schema_unflatten(
      schema,
      key,
      flat,
      alloc,
      out,
    );
  }

  late final _guatiao_schema_unflattenPtr = _lookup<
      ffi.NativeFunction<
          guatiao_status$1 Function(
              ffi.Pointer<guatiao_value>,
              guatiao_str,
              ffi.Pointer<guatiao_value>,
              ffi.Pointer<guatiao_alloc>,
              ffi.Pointer<guatiao_value>)>>('guatiao_schema_unflatten');
  late final _guatiao_schema_unflatten =
      _guatiao_schema_unflattenPtr.asFunction<
          int Function(
              ffi.Pointer<guatiao_value>,
              guatiao_str,
              ffi.Pointer<guatiao_value>,
              ffi.Pointer<guatiao_alloc>,
              ffi.Pointer<guatiao_value>)>();

  int guatiao_schema_validate(
    ffi.Pointer<guatiao_value> schema,
    ffi.Pointer<guatiao_value> config,
    ffi.Pointer<guatiao_alloc> alloc,
    ffi.Pointer<guatiao_value> out_error,
  ) {
    return _guatiao_schema_validate(
      schema,
      config,
      alloc,
      out_error,
    );
  }

  late final _guatiao_schema_validatePtr = _lookup<
      ffi.NativeFunction<
          guatiao_status$1 Function(
              ffi.Pointer<guatiao_value>,
              ffi.Pointer<guatiao_value>,
              ffi.Pointer<guatiao_alloc>,
              ffi.Pointer<guatiao_value>)>>('guatiao_schema_validate');
  late final _guatiao_schema_validate = _guatiao_schema_validatePtr.asFunction<
      int Function(ffi.Pointer<guatiao_value>, ffi.Pointer<guatiao_value>,
          ffi.Pointer<guatiao_alloc>, ffi.Pointer<guatiao_value>)>();

  int guatiao_string_push(
    ffi.Pointer<guatiao_alloc> alloc,
    ffi.Pointer<guatiao_value> node,
    guatiao_str text,
  ) {
    return _guatiao_string_push(
      alloc,
      node,
      text,
    );
  }

  late final _guatiao_string_pushPtr = _lookup<
      ffi.NativeFunction<
          guatiao_status$1 Function(ffi.Pointer<guatiao_alloc>,
              ffi.Pointer<guatiao_value>, guatiao_str)>>('guatiao_string_push');
  late final _guatiao_string_push = _guatiao_string_pushPtr.asFunction<
      int Function(ffi.Pointer<guatiao_alloc>, ffi.Pointer<guatiao_value>,
          guatiao_str)>();

  int guatiao_value_absent(
    ffi.Pointer<guatiao_value> out,
  ) {
    return _guatiao_value_absent(
      out,
    );
  }

  late final _guatiao_value_absentPtr = _lookup<
      ffi.NativeFunction<
          guatiao_status$1 Function(
              ffi.Pointer<guatiao_value>)>>('guatiao_value_absent');
  late final _guatiao_value_absent = _guatiao_value_absentPtr
      .asFunction<int Function(ffi.Pointer<guatiao_value>)>();

  int guatiao_value_bool(
    bool b,
    ffi.Pointer<guatiao_value> out,
  ) {
    return _guatiao_value_bool(
      b,
      out,
    );
  }

  late final _guatiao_value_boolPtr = _lookup<
      ffi.NativeFunction<
          guatiao_status$1 Function(
              ffi.Bool, ffi.Pointer<guatiao_value>)>>('guatiao_value_bool');
  late final _guatiao_value_bool = _guatiao_value_boolPtr
      .asFunction<int Function(bool, ffi.Pointer<guatiao_value>)>();

  int guatiao_value_bytes(
    ffi.Pointer<guatiao_alloc> alloc,
    guatiao_bytes bytes,
    ffi.Pointer<guatiao_value> out,
  ) {
    return _guatiao_value_bytes(
      alloc,
      bytes,
      out,
    );
  }

  late final _guatiao_value_bytesPtr = _lookup<
      ffi.NativeFunction<
          guatiao_status$1 Function(ffi.Pointer<guatiao_alloc>, guatiao_bytes,
              ffi.Pointer<guatiao_value>)>>('guatiao_value_bytes');
  late final _guatiao_value_bytes = _guatiao_value_bytesPtr.asFunction<
      int Function(ffi.Pointer<guatiao_alloc>, guatiao_bytes,
          ffi.Pointer<guatiao_value>)>();

  int guatiao_value_clone(
    ffi.Pointer<guatiao_alloc> alloc,
    ffi.Pointer<guatiao_value> src,
    ffi.Pointer<guatiao_value> out,
  ) {
    return _guatiao_value_clone(
      alloc,
      src,
      out,
    );
  }

  late final _guatiao_value_clonePtr = _lookup<
      ffi.NativeFunction<
          guatiao_status$1 Function(
              ffi.Pointer<guatiao_alloc>,
              ffi.Pointer<guatiao_value>,
              ffi.Pointer<guatiao_value>)>>('guatiao_value_clone');
  late final _guatiao_value_clone = _guatiao_value_clonePtr.asFunction<
      int Function(ffi.Pointer<guatiao_alloc>, ffi.Pointer<guatiao_value>,
          ffi.Pointer<guatiao_value>)>();

  int guatiao_value_free(
    ffi.Pointer<guatiao_value> v,
  ) {
    return _guatiao_value_free(
      v,
    );
  }

  late final _guatiao_value_freePtr = _lookup<
      ffi.NativeFunction<
          guatiao_status$1 Function(
              ffi.Pointer<guatiao_value>)>>('guatiao_value_free');
  late final _guatiao_value_free = _guatiao_value_freePtr
      .asFunction<int Function(ffi.Pointer<guatiao_value>)>();

  int guatiao_value_list(
    ffi.Pointer<guatiao_alloc> alloc,
    ffi.Pointer<guatiao_value> out,
  ) {
    return _guatiao_value_list(
      alloc,
      out,
    );
  }

  late final _guatiao_value_listPtr = _lookup<
      ffi.NativeFunction<
          guatiao_status$1 Function(ffi.Pointer<guatiao_alloc>,
              ffi.Pointer<guatiao_value>)>>('guatiao_value_list');
  late final _guatiao_value_list = _guatiao_value_listPtr.asFunction<
      int Function(ffi.Pointer<guatiao_alloc>, ffi.Pointer<guatiao_value>)>();

  int guatiao_value_map(
    ffi.Pointer<guatiao_alloc> alloc,
    ffi.Pointer<guatiao_value> out,
  ) {
    return _guatiao_value_map(
      alloc,
      out,
    );
  }

  late final _guatiao_value_mapPtr = _lookup<
      ffi.NativeFunction<
          guatiao_status$1 Function(ffi.Pointer<guatiao_alloc>,
              ffi.Pointer<guatiao_value>)>>('guatiao_value_map');
  late final _guatiao_value_map = _guatiao_value_mapPtr.asFunction<
      int Function(ffi.Pointer<guatiao_alloc>, ffi.Pointer<guatiao_value>)>();

  int guatiao_value_null(
    ffi.Pointer<guatiao_value> out,
  ) {
    return _guatiao_value_null(
      out,
    );
  }

  late final _guatiao_value_nullPtr = _lookup<
      ffi.NativeFunction<
          guatiao_status$1 Function(
              ffi.Pointer<guatiao_value>)>>('guatiao_value_null');
  late final _guatiao_value_null = _guatiao_value_nullPtr
      .asFunction<int Function(ffi.Pointer<guatiao_value>)>();

  int guatiao_value_number(
    ffi.Pointer<guatiao_alloc> alloc,
    guatiao_str text,
    ffi.Pointer<guatiao_value> out,
  ) {
    return _guatiao_value_number(
      alloc,
      text,
      out,
    );
  }

  late final _guatiao_value_numberPtr = _lookup<
      ffi.NativeFunction<
          guatiao_status$1 Function(ffi.Pointer<guatiao_alloc>, guatiao_str,
              ffi.Pointer<guatiao_value>)>>('guatiao_value_number');
  late final _guatiao_value_number = _guatiao_value_numberPtr.asFunction<
      int Function(ffi.Pointer<guatiao_alloc>, guatiao_str,
          ffi.Pointer<guatiao_value>)>();

  int guatiao_value_string(
    ffi.Pointer<guatiao_alloc> alloc,
    guatiao_str text,
    ffi.Pointer<guatiao_value> out,
  ) {
    return _guatiao_value_string(
      alloc,
      text,
      out,
    );
  }

  late final _guatiao_value_stringPtr = _lookup<
      ffi.NativeFunction<
          guatiao_status$1 Function(ffi.Pointer<guatiao_alloc>, guatiao_str,
              ffi.Pointer<guatiao_value>)>>('guatiao_value_string');
  late final _guatiao_value_string = _guatiao_value_stringPtr.asFunction<
      int Function(ffi.Pointer<guatiao_alloc>, guatiao_str,
          ffi.Pointer<guatiao_value>)>();
}

const int GUATIAO_ABI_VERSION = 1;

const int GUATIAO_BYTES_ARRAY = 2;

const int GUATIAO_BYTES_BASE64 = 1;

const int GUATIAO_BYTES_DATA_URI = 0;

const int GUATIAO_BYTES_REFUSE = 3;

const String GUATIAO_KEY_ADDITIONAL_PROPERTIES = 'additionalProperties';

const String GUATIAO_KEY_ANY_OF = 'anyOf';

const String GUATIAO_KEY_CONST = 'const';

const String GUATIAO_KEY_DEFAULT = 'default';

const String GUATIAO_KEY_DESCRIPTION = 'description';

const String GUATIAO_KEY_DIALECT =
    'https://json-schema.org/draft/2020-12/schema';

const String GUATIAO_KEY_ENUM = 'enum';

const String GUATIAO_KEY_ITEMS = 'items';

const String GUATIAO_KEY_MAXIMUM = 'maximum';

const String GUATIAO_KEY_MINIMUM = 'minimum';

const String GUATIAO_KEY_ONE_OF = 'oneOf';

const String GUATIAO_KEY_PROPERTIES = 'properties';

const String GUATIAO_KEY_REQUIRED = 'required';

const String GUATIAO_KEY_SCHEMA = '\$schema';

const String GUATIAO_KEY_TITLE = 'title';

const String GUATIAO_KEY_TYPE = 'type';

const String GUATIAO_KEY_TYPE_ARRAY = 'array';

const String GUATIAO_KEY_TYPE_BOOLEAN = 'boolean';

const String GUATIAO_KEY_TYPE_BYTES = 'bytes';

const String GUATIAO_KEY_TYPE_INTEGER = 'integer';

const String GUATIAO_KEY_TYPE_NUMBER = 'number';

const String GUATIAO_KEY_TYPE_OBJECT = 'object';

const String GUATIAO_KEY_TYPE_STRING = 'string';

const String GUATIAO_KEY_X_ADVANCED = 'x-advanced';

const String GUATIAO_KEY_X_ENUM_LABELS = 'x-enum-labels';

const String GUATIAO_KEY_X_ORDER = 'x-order';

const String GUATIAO_KEY_X_SECTION = 'x-section';

const String GUATIAO_KEY_X_SENSITIVE = 'x-sensitive';

const String GUATIAO_KEY_X_VARIANT_TAG = 'x-variant-tag';

const int GUATIAO_MAX_DEPTH = 128;

const int GUATIAO_MERGE_DEEP = 2;

const int GUATIAO_MERGE_OPT_MERGELISTS = 1;

const int GUATIAO_MERGE_SIMPLE = 1;

const int GUATIAO_MERGE_SUBSTITUTE = 3;

const int GUATIAO_PAYLOAD_SEPARATOR = 46;

const int GUATIAO_PRETTY = 512;

const int GUATIAO_READ_DATA_URIS = 256;

final class guatiao_alloc extends ffi.Struct {
  @ffi.Uint32()
  external int struct_size;

  external ffi.Pointer<ffi.Void> ctx;

  external ffi.Pointer<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Void> Function(
              ffi.Pointer<ffi.Void> ctx, ffi.Size size, ffi.Size align)>> alloc;

  external ffi.Pointer<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<ffi.Void> ctx,
              ffi.Pointer<ffi.Void> ptr, ffi.Size size, ffi.Size align)>> free;

  external ffi
      .Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void> ctx)>>
      release;

  static ffi.Pointer<guatiao_alloc> $allocate(
    ffi.Allocator $allocator, {
    required int struct_size,
    required ffi.Pointer<ffi.Void> ctx,
    required ffi.Pointer<
            ffi.NativeFunction<
                ffi.Pointer<ffi.Void> Function(
                    ffi.Pointer<ffi.Void> ctx, ffi.Size size, ffi.Size align)>>
        alloc,
    required ffi.Pointer<
            ffi.NativeFunction<
                ffi.Void Function(ffi.Pointer<ffi.Void> ctx,
                    ffi.Pointer<ffi.Void> ptr, ffi.Size size, ffi.Size align)>>
        free,
    required ffi.Pointer<
            ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void> ctx)>>
        release,
  }) =>
      $allocator<guatiao_alloc>()
        ..ref.struct_size = struct_size
        ..ref.ctx = ctx
        ..ref.alloc = alloc
        ..ref.free = free
        ..ref.release = release;
}

final class guatiao_buffer extends ffi.Struct {
  external ffi.Pointer<ffi.Uint8> ptr;

  @ffi.Size()
  external int len;

  @ffi.Size()
  external int cap;

  external ffi.Pointer<guatiao_alloc> alloc;

  static ffi.Pointer<guatiao_buffer> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<ffi.Uint8> ptr,
    required int len,
    required int cap,
    required ffi.Pointer<guatiao_alloc> alloc,
  }) =>
      $allocator<guatiao_buffer>()
        ..ref.ptr = ptr
        ..ref.len = len
        ..ref.cap = cap
        ..ref.alloc = alloc;
}

final class guatiao_bytes extends ffi.Struct {
  external ffi.Pointer<ffi.Uint8> ptr;

  @ffi.Size()
  external int len;

  static ffi.Pointer<guatiao_bytes> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<ffi.Uint8> ptr,
    required int len,
  }) =>
      $allocator<guatiao_bytes>()
        ..ref.ptr = ptr
        ..ref.len = len;
}

final class guatiao_bytes_mut extends ffi.Struct {
  external ffi.Pointer<ffi.Uint8> ptr;

  @ffi.Size()
  external int len;

  static ffi.Pointer<guatiao_bytes_mut> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<ffi.Uint8> ptr,
    required int len,
  }) =>
      $allocator<guatiao_bytes_mut>()
        ..ref.ptr = ptr
        ..ref.len = len;
}

final class guatiao_entries extends ffi.Struct {
  external ffi.Pointer<guatiao_entry> ptr;

  @ffi.Size()
  external int len;

  static ffi.Pointer<guatiao_entries> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<guatiao_entry> ptr,
    required int len,
  }) =>
      $allocator<guatiao_entries>()
        ..ref.ptr = ptr
        ..ref.len = len;
}

final class guatiao_entry extends ffi.Struct {
  external guatiao_string key;

  external guatiao_value value;
}

final class guatiao_host_info extends ffi.Struct {
  @ffi.Uint32()
  external int struct_size;

  @ffi.Uint32()
  external int abi_version;

  external guatiao_str host_id;

  external guatiao_str host_version;

  external ffi.Pointer<guatiao_alloc> alloc;

  external guatiao_map_ptr meta;

  external ffi.Pointer<guatiao_host_services> services;
}

final class guatiao_host_services extends ffi.Struct {
  @ffi.Uint32()
  external int struct_size;

  external ffi.Pointer<ffi.Void> ctx;

  external ffi.Pointer<
      ffi.NativeFunction<
          guatiao_status$1 Function(ffi.Pointer<ffi.Void> ctx, guatiao_str key,
              ffi.Pointer<ffi.Pointer<guatiao_provider_info>> out)>> get;

  external ffi.Pointer<
      ffi.NativeFunction<
          guatiao_status$1 Function(
              ffi.Pointer<ffi.Void> ctx,
              guatiao_str kind,
              ffi.Pointer<ffi.Pointer<guatiao_provider_info>> out,
              ffi.Size cap,
              ffi.Pointer<ffi.Size> total)>> list;

  external ffi.Pointer<
          ffi.NativeFunction<
              ffi.Pointer<guatiao_alloc> Function(ffi.Pointer<ffi.Void> ctx)>>
      alloc;

  static ffi.Pointer<guatiao_host_services> $allocate(
    ffi.Allocator $allocator, {
    required int struct_size,
    required ffi.Pointer<ffi.Void> ctx,
    required ffi.Pointer<
            ffi.NativeFunction<
                guatiao_status$1 Function(
                    ffi.Pointer<ffi.Void> ctx,
                    guatiao_str key,
                    ffi.Pointer<ffi.Pointer<guatiao_provider_info>> out)>>
        get,
    required ffi.Pointer<
            ffi.NativeFunction<
                guatiao_status$1 Function(
                    ffi.Pointer<ffi.Void> ctx,
                    guatiao_str kind,
                    ffi.Pointer<ffi.Pointer<guatiao_provider_info>> out,
                    ffi.Size cap,
                    ffi.Pointer<ffi.Size> total)>>
        list,
    required ffi.Pointer<
            ffi.NativeFunction<
                ffi.Pointer<guatiao_alloc> Function(ffi.Pointer<ffi.Void> ctx)>>
        alloc,
  }) =>
      $allocator<guatiao_host_services>()
        ..ref.struct_size = struct_size
        ..ref.ctx = ctx
        ..ref.get = get
        ..ref.list = list
        ..ref.alloc = alloc;
}

final class guatiao_kind_header extends ffi.Struct {
  @ffi.Uint32()
  external int struct_size;

  @ffi.Uint32()
  external int floor_hash;

  static ffi.Pointer<guatiao_kind_header> $allocate(
    ffi.Allocator $allocator, {
    required int struct_size,
    required int floor_hash,
  }) =>
      $allocator<guatiao_kind_header>()
        ..ref.struct_size = struct_size
        ..ref.floor_hash = floor_hash;
}

final class guatiao_kind_table extends ffi.Struct {
  @ffi.Uint32()
  external int struct_size;

  @ffi.Uint32()
  external int vtable_size;

  external guatiao_str kind;

  external ffi.Pointer<ffi.Void> vtable;
}

final class guatiao_kind_tables extends ffi.Struct {
  external ffi.Pointer<guatiao_kind_table> ptr;

  @ffi.Size()
  external int len;

  @ffi.Size()
  external int stride;

  static ffi.Pointer<guatiao_kind_tables> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<guatiao_kind_table> ptr,
    required int len,
    required int stride,
  }) =>
      $allocator<guatiao_kind_tables>()
        ..ref.ptr = ptr
        ..ref.len = len
        ..ref.stride = stride;
}

final class guatiao_kinds extends ffi.Struct {
  external ffi.Pointer<guatiao_str> ptr;

  @ffi.Size()
  external int len;

  static ffi.Pointer<guatiao_kinds> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<guatiao_str> ptr,
    required int len,
  }) =>
      $allocator<guatiao_kinds>()
        ..ref.ptr = ptr
        ..ref.len = len;
}

final class guatiao_library_info extends ffi.Struct {
  @ffi.Uint32()
  external int struct_size;

  @ffi.Uint32()
  external int abi_version;

  external guatiao_str id;

  external guatiao_str version;

  external guatiao_providers providers;

  external guatiao_map_ptr meta;

  external ffi.Pointer<ffi.NativeFunction<guatiao_status$1 Function()>> unload;
}

final class guatiao_list extends ffi.Struct {
  external ffi.Pointer<guatiao_value> ptr;

  @ffi.Size()
  external int len;

  @ffi.Size()
  external int cap;

  external ffi.Pointer<guatiao_alloc> alloc;

  static ffi.Pointer<guatiao_list> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<guatiao_value> ptr,
    required int len,
    required int cap,
    required ffi.Pointer<guatiao_alloc> alloc,
  }) =>
      $allocator<guatiao_list>()
        ..ref.ptr = ptr
        ..ref.len = len
        ..ref.cap = cap
        ..ref.alloc = alloc;
}

final class guatiao_map extends ffi.Struct {
  external ffi.Pointer<guatiao_entry> ptr;

  @ffi.Size()
  external int len;

  @ffi.Size()
  external int cap;

  external ffi.Pointer<guatiao_alloc> alloc;

  static ffi.Pointer<guatiao_map> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<guatiao_entry> ptr,
    required int len,
    required int cap,
    required ffi.Pointer<guatiao_alloc> alloc,
  }) =>
      $allocator<guatiao_map>()
        ..ref.ptr = ptr
        ..ref.len = len
        ..ref.cap = cap
        ..ref.alloc = alloc;
}

typedef guatiao_map_ptr = ffi.Pointer<guatiao_map>;

final class guatiao_merge_override extends ffi.Struct {
  external guatiao_str path;

  @ffi.Uint32()
  external int mode;
}

typedef guatiao_number = guatiao_string;

final class guatiao_object extends ffi.Struct {
  external ffi.Pointer<ffi.Void> table;

  @ffi.Size()
  external int size;

  external ffi.Pointer<ffi.Void> ctx;

  static ffi.Pointer<guatiao_object> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<ffi.Void> table,
    required int size,
    required ffi.Pointer<ffi.Void> ctx,
  }) =>
      $allocator<guatiao_object>()
        ..ref.table = table
        ..ref.size = size
        ..ref.ctx = ctx;
}

final class guatiao_payload extends ffi.Union {
  @ffi.Bool()
  external bool b;

  external guatiao_string text;

  external guatiao_number number;

  external guatiao_buffer bytes;

  external guatiao_list list;

  external guatiao_map map;
}

final class guatiao_provider_error extends ffi.Struct {
  @guatiao_status$1()
  external int status;

  external guatiao_string message;
}

final class guatiao_provider_info extends ffi.Struct {
  @ffi.Uint32()
  external int struct_size;

  @ffi.Uint32()
  external int vtable_size;

  external guatiao_kinds kinds;

  external guatiao_str id;

  external guatiao_str display_name;

  external ffi.Pointer<guatiao_value> config;

  external ffi.Pointer<ffi.Void> vtable;

  external ffi.Pointer<ffi.Void> ctx;

  external guatiao_map_ptr meta;

  external guatiao_str version;

  external ffi.Pointer<
          ffi.NativeFunction<
              ffi.Bool Function(
                  ffi.Pointer<ffi.Void> ctx, ffi.Pointer<guatiao_str> reason)>>
      available;

  external guatiao_kind_tables tables;

  external ffi.Pointer<
      ffi.NativeFunction<
          guatiao_status$1 Function(
              ffi.Pointer<ffi.Void> ctx,
              ffi.Pointer<guatiao_value> config,
              ffi.Pointer<ffi.Pointer<ffi.Void>> out,
              ffi.Pointer<guatiao_provider_error> err)>> create;

  external ffi.Pointer<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Pointer<ffi.Void> ctx, ffi.Pointer<ffi.Void> instance)>>
      destroy;
}

final class guatiao_providers extends ffi.Struct {
  external ffi.Pointer<guatiao_provider_info> ptr;

  @ffi.Size()
  external int len;

  @ffi.Size()
  external int stride;

  static ffi.Pointer<guatiao_providers> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<guatiao_provider_info> ptr,
    required int len,
    required int stride,
  }) =>
      $allocator<guatiao_providers>()
        ..ref.ptr = ptr
        ..ref.len = len
        ..ref.stride = stride;
}

final class guatiao_registry extends ffi.Opaque {}

enum guatiao_status {
  GUATIAO_OK(0),
  GUATIAO_ERR_BAD_VALUE(7),
  GUATIAO_ERR_ALLOC(8),
  GUATIAO_ERR_WRONG_KIND(9),
  GUATIAO_ERR_NOT_FOUND(10),
  GUATIAO_ERR_NULL(11),
  GUATIAO_ERR_GONE(12),
  GUATIAO_ERR_UNSUPPORTED(13),
  GUATIAO_ERR_BUSY(14),
  GUATIAO_ERR_INTERNAL(100);

  final int value;
  const guatiao_status(this.value);

  static guatiao_status fromValue(int value) => switch (value) {
        0 => GUATIAO_OK,
        7 => GUATIAO_ERR_BAD_VALUE,
        8 => GUATIAO_ERR_ALLOC,
        9 => GUATIAO_ERR_WRONG_KIND,
        10 => GUATIAO_ERR_NOT_FOUND,
        11 => GUATIAO_ERR_NULL,
        12 => GUATIAO_ERR_GONE,
        13 => GUATIAO_ERR_UNSUPPORTED,
        14 => GUATIAO_ERR_BUSY,
        100 => GUATIAO_ERR_INTERNAL,
        _ => throw ArgumentError('Unknown value for guatiao_status: $value'),
      };
}

typedef guatiao_status$1 = ffi.Uint32;
typedef Dartguatiao_status = int;

final class guatiao_str extends ffi.Struct {
  external ffi.Pointer<ffi.Uint8> ptr;

  @ffi.Size()
  external int len;

  static ffi.Pointer<guatiao_str> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<ffi.Uint8> ptr,
    required int len,
  }) =>
      $allocator<guatiao_str>()
        ..ref.ptr = ptr
        ..ref.len = len;
}

final class guatiao_string extends ffi.Struct {
  external ffi.Pointer<ffi.Uint8> ptr;

  @ffi.Size()
  external int len;

  @ffi.Size()
  external int cap;

  external ffi.Pointer<guatiao_alloc> alloc;

  static ffi.Pointer<guatiao_string> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<ffi.Uint8> ptr,
    required int len,
    required int cap,
    required ffi.Pointer<guatiao_alloc> alloc,
  }) =>
      $allocator<guatiao_string>()
        ..ref.ptr = ptr
        ..ref.len = len
        ..ref.cap = cap
        ..ref.alloc = alloc;
}

enum guatiao_tag {
  GUATIAO_ABSENT(0),
  GUATIAO_NULL(1),
  GUATIAO_BOOL(2),
  GUATIAO_NUMBER(3),
  GUATIAO_STRING(4),
  GUATIAO_BYTES(5),
  GUATIAO_LIST(6),
  GUATIAO_MAP(7);

  final int value;
  const guatiao_tag(this.value);

  static guatiao_tag fromValue(int value) => switch (value) {
        0 => GUATIAO_ABSENT,
        1 => GUATIAO_NULL,
        2 => GUATIAO_BOOL,
        3 => GUATIAO_NUMBER,
        4 => GUATIAO_STRING,
        5 => GUATIAO_BYTES,
        6 => GUATIAO_LIST,
        7 => GUATIAO_MAP,
        _ => throw ArgumentError('Unknown value for guatiao_tag: $value'),
      };
}

typedef guatiao_tag$1 = ffi.Uint32;
typedef Dartguatiao_tag = int;

final class guatiao_value extends ffi.Struct {
  @ffi.Uint32()
  external int tag;

  @ffi.Uint32()
  external int _pad;

  external guatiao_payload payload;
}

final class guatiao_values extends ffi.Struct {
  external ffi.Pointer<guatiao_value> ptr;

  @ffi.Size()
  external int len;

  static ffi.Pointer<guatiao_values> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<guatiao_value> ptr,
    required int len,
  }) =>
      $allocator<guatiao_values>()
        ..ref.ptr = ptr
        ..ref.len = len;
}
