/*
 * guatiao -- the C form of the value model.
 *
 * GENERATED BY cbindgen, from build.rs. DO NOT EDIT BY HAND.
 * Regenerate with:
 *   GUATIAO_WRITE_HEADER=1 cargo build -p guatiao --features c-header
 * The build script renders this on every build and a test compares the
 * committed file against it, so an edit to the Rust that is not
 * regenerated fails the suite rather than shipping a header describing a
 * different ABI.
 *
 * ----------------------------------------------------------------------
 * READING A VALUE NEEDS NO LIBRARY AT ALL.
 *
 * Every type here is a plain struct or union, and the accessors at the
 * bottom of this file are `static inline`. You can read a whole tree --
 * walk a map, pull out a number's exact text -- with nothing linked.
 * Building and freeing one needs code; those functions are declared in
 * the middle of this file and are exported by any shared library built
 * from the guatiao crate.
 *
 * Strings and slices cross as pointer + length, never NUL-terminated, so
 * a key or a value may contain a NUL. Compare keys with
 * guatiao_str_eq(), never strcmp().
 *
 * A VIEW is {ptr, len} and is what every read hands back. An OWNED
 * container is {ptr, len, cap, alloc} and can be grown. A capacity of 0
 * means the buffer is NOT owned -- a literal, or a borrow -- and is never
 * freed, which is what lets you write a whole tree as a brace
 * initialiser and still pass it to guatiao_value_free().
 *
 * CHECK A VIEW'S LENGTH BEFORE ITS POINTER. An empty view may carry a
 * dangling pointer; it is never dereferenced when the length is zero.
 * ----------------------------------------------------------------------
 */


#ifndef GUATIAO_H
#define GUATIAO_H

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <errno.h>
#include <limits.h>

/* Forward declarations, so a container can hold a pointer to a type that
 * is not defined yet. Each of these types is defined at the BOTTOM of this
 * file, for the reason in cbindgen.toml: the type graph has by-value
 * cycles that a generator's traversal cannot order for C, and only an
 * explicit forward declaration breaks them.
 *
 * A pointer to an incomplete type is fine; a FIELD of one is not, which is
 * exactly which types had to move. */
typedef struct guatiao_entry guatiao_entry;


/*
 How deep a tree [`value_clone`] will follow.

 Configuration trees are a handful of levels deep; this is far above any
 real one and far below what would exhaust a stack. It exists so a
 hostile or corrupt tree is an error rather than a dead process.
 */
#define MAX_DEPTH 128

/*
 Shallow: top-level keys replace, nested maps are not recursed into.
 */
#define GUATIAO_MERGE_SIMPLE 1

/*
 Recursive maps, lists extended with unique items.
 */
#define GUATIAO_MERGE_DEEP 2

/*
 Recursive maps, wholesale list replacement. The default.
 */
#define GUATIAO_MERGE_SUBSTITUTE 3

/*
 `mergelists`: [`GUATIAO_MERGE_DEEP`] merges map elements of a list by
 position rather than appending them.
 */
#define GUATIAO_MERGE_OPT_MERGELISTS 1

/*
 The envelope's own version, for a library that wants to refuse a host
 it does not understand.

 Bumped only for a change no `struct_size` guard can express. Appending
 a field is not such a change.
 */
#define GUATIAO_ABI_VERSION 1

/*
 Between a field's key and one of its payload fields.
 */
#define GUATIAO_PAYLOAD_SEPARATOR '.'

/*
 What an entry point reports.

 The numbering is wider than the list because these values come from a
 status space a host application may share with the crates it embeds, so
 one `switch` in a consumer can cover both. A consumer with no such
 space reads 0 as success and treats every other value as failure, which
 is the whole contract.
 */
enum guatiao_status
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
  /*
   The operation happened.
   */
  GUATIAO_OK = 0,
  /*
   A value could not be stored: text offered as a number that is not
   one, or bytes offered as text that are not UTF-8. Nothing was
   written.
   */
  GUATIAO_ERR_BAD_VALUE = 7,
  /*
   The allocator could not satisfy the request, or was unusable.
   Nothing was written.
   */
  GUATIAO_ERR_ALLOC = 8,
  /*
   The operation does not apply to this value's kind.
   */
  GUATIAO_ERR_WRONG_KIND = 9,
  /*
   A key or index was not there.
   */
  GUATIAO_ERR_NOT_FOUND = 10,
  /*
   A required pointer was null.
   */
  GUATIAO_ERR_NULL = 11,
  /*
   A callback unwound, or a panic was caught at this boundary. The
   operation did not happen; the process is still usable.
   */
  GUATIAO_ERR_INTERNAL = 100,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum guatiao_status guatiao_status;
#else
typedef uint32_t guatiao_status;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/*
 The kind of a stored value.

 **This type is deliberately NOT used as a field type.** It exists to
 give C an enum it can switch on and a debugger can print by name;
 A value's `tag` field is a plain `uint32_t`.

 The distinction is a soundness one and the layout is identical either
 way (measured). A Rust `#[repr(u32)]` enum has a *restricted set of
 valid values*, so a ninth bit pattern arriving from a foreign caller
 would be undefined behaviour the instant the struct is read — before
 any `match`, before anything could reject it. As a `uint32_t` it is
 merely an integer out of range, which a reader skips.

 **New kinds are APPENDED.** A reader meeting a tag it does not know
 must skip that one value and render the rest; that is the whole
 forward-compatibility story, and it works only if numbers never move.
 */
enum guatiao_tag
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
  /*
   No value: the answer to a lookup that found nothing, and the tag of
   an optional slot that is not filled in. Never stored in a list.
   */
  GUATIAO_ABSENT = 0,
  /*
   The stored nothing. Distinct from absent, the same way JSON
   distinguishes a missing member from a null one.
   */
  GUATIAO_NULL = 1,
  GUATIAO_BOOL = 2,
  /*
   A number, carried as the exact text that declared it. Read it with
   `guatiao_value_number`, not `guatiao_value_str`.
   */
  GUATIAO_NUMBER = 3,
  GUATIAO_STRING = 4,
  GUATIAO_BYTES = 5,
  GUATIAO_LIST = 6,
  GUATIAO_MAP = 7,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum guatiao_tag guatiao_tag;
#else
typedef uint32_t guatiao_tag;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/*
 A host's registry of loaded libraries.

 Opaque: create one with [`guatiao_registry_new`] and release it with
 [`guatiao_registry_free`]. Every other function here takes the pointer
 that gave you.

 **Not thread-safe.** One registry is one host's table, and the loading
 it does is not reentrant; a host sharing one across threads guards it
 itself, as it would any other mutable object it owns.
 */
typedef struct guatiao_registry guatiao_registry;

/*
 Borrowed UTF-8 text: a pointer and a length, no NUL terminator.

 **Check `len` before `ptr`.** An empty view may carry a dangling or
 null pointer, and the pointer must not be touched when the length is
 zero.
 */
typedef struct guatiao_str {
  /*
   First byte. May be null or dangling when `len` is 0.
   */
  const uint8_t *ptr;
  /*
   Length in bytes.
   */
  size_t len;
} guatiao_str;

/*
 An allocator, as a vtable a foreign caller can fill in.

 Every field after `struct_size` is read only when `struct_size` says it
 is there, so fields may be **appended** without breaking a caller
 compiled against an older copy.
 */
typedef struct guatiao_alloc {
  /*
   `sizeof(guatiao_alloc)` as the caller compiled it. Always first,
   always set. Zero is refused rather than read charitably.
   */
  uint32_t struct_size;
  /*
   Passed back to every callback below. Opaque to this crate.
   */
  void *ctx;
  /*
   Required. A null here is refused at the boundary rather than
   called.

   Spelled out rather than written as the type alias above, and that
   is a header-generation constraint rather than a style: through an
   alias, a header generator renders this field as an opaque struct
   used by value, which is an incomplete type and compiles nowhere.
   */
  void *(*alloc)(void *ctx, size_t size, size_t align);
  /*
   Required. A null here is refused at the boundary rather than
   called. Spelled out for the reason given on `alloc`.
   */
  void (*free)(void *ctx, void *ptr, size_t size, size_t align);
  /*
   Optional, and the newest field. A caller compiled before it existed
   declares a smaller `struct_size` and it reads as absent — never as
   whatever bytes happened to follow that caller's allocation.
   */
  void (*release)(void *ctx);
} guatiao_alloc;

/*
 Owned, growable UTF-8 text.

 `cap == 0` means the buffer is **not owned**: a literal or a borrow,
 never freed, copied out of on the first growth.
 */
typedef struct guatiao_string {
  /*
   First byte. Never null for an owned buffer; dangling-but-aligned
   when the container is empty.
   */
  uint8_t *ptr;
  /*
   Length in bytes.
   */
  size_t len;
  /*
   Capacity in bytes. 0 means the buffer is not owned.
   */
  size_t cap;
  /*
   The allocator that made this buffer, and the only one that may
   grow or free it. Null when `cap == 0`.
   */
  const struct guatiao_alloc *alloc;
} guatiao_string;

/*
 Owned, growable bytes. See `guatiao_string` for the `cap` rule.
 */
typedef struct guatiao_buffer {
  /*
   First byte.
   */
  uint8_t *ptr;
  /*
   Length in bytes.
   */
  size_t len;
  /*
   Capacity in bytes. 0 means the buffer is not owned.
   */
  size_t cap;
  /*
   The allocator that made this buffer. Null when `cap == 0`.
   */
  const struct guatiao_alloc *alloc;
} guatiao_buffer;

/*
 An owned, growable sequence of values.
 */
typedef struct guatiao_list {
  /*
   First element.
   */
  struct guatiao_value *ptr;
  /*
   Number of elements.
   */
  size_t len;
  /*
   Capacity in elements. 0 means the buffer is not owned.
   */
  size_t cap;
  /*
   The allocator that made this buffer. Null when `cap == 0`.
   */
  const struct guatiao_alloc *alloc;
} guatiao_list;

/*
 An owned, growable sequence of key/value pairs, in insertion order.

 Lookup is a linear scan, by contract rather than by accident: this is a
 metadata container holding tens of keys, and at that size a scan over
 contiguous memory beats hashing every lookup key. Setting an existing
 key replaces it **in place**, keeping its position.
 */
typedef struct guatiao_map {
  /*
   First entry.
   */
  guatiao_entry *ptr;
  /*
   Number of entries.
   */
  size_t len;
  /*
   Capacity in entries. 0 means the buffer is not owned.
   */
  size_t cap;
  /*
   The allocator that made this buffer. Null when `cap == 0`.
   */
  const struct guatiao_alloc *alloc;
} guatiao_map;

/*
 The payload of a value. Which arm is live is decided by the
 tag, and by nothing else.

 # Reading an arm

 Reading a 32-byte arm off the wrong tag is garbage but defined: all
 four are structs of pointers and integers, which have no validity
 constraint beyond being initialised. Reading the `b` arm off the wrong
 tag is **undefined behaviour** — `bool` is the one arm with a
 restricted value set.

 Both are prevented by one rule the constructors obey without
 exception: **every node is born with all 40 bytes initialised**. A
 payload written as `{ b: true }` alone initialises a single byte and
 leaves thirty-one uninitialised, and reading any wide arm off that is
 undefined too. Nothing in the toolchain warns about either.

 The arms are `ManuallyDrop` because a union field must be `Copy` or
 wrapped, and making an allocator-carrying container `Copy` would invite
 a silent double free. It costs nothing at the boundary: a header
 generator erases the wrapper entirely.
 */
typedef union guatiao_payload {
  /*
   Live when the tag is `GUATIAO_BOOL`. Zero is false, **any**
   non-zero byte is true.

   A byte rather than a `bool`, and that is the one place this design
   deliberately refuses a nicer-looking type. A `bool` has a
   *restricted set of valid values* — it must be 0 or 1 — so a byte
   that is neither would be undefined behaviour to read at that type,
   at the moment of the read, before any check could reject it. A
   producer can write one without trying: a cast, a union, an
   uninitialised local.

   `u8` has no invalid bit patterns, so the hazard does not exist
   rather than being defended against at every read. It is the same
   reason the tag is a `u32` and not an enum, and it costs a C caller
   nothing: `.b = true` still stores 1.
   */
  uint8_t b;
  /*
   Live when the tag is `GUATIAO_STRING` **or** `GUATIAO_NUMBER`.
   */
  struct guatiao_string text;
  /*
   Live when the tag is `GUATIAO_BYTES`.
   */
  struct guatiao_buffer bytes;
  /*
   Live when the tag is `GUATIAO_LIST`.
   */
  struct guatiao_list list;
  /*
   Live when the tag is `GUATIAO_MAP`.
   */
  struct guatiao_map map;
} guatiao_payload;

/*
 One value: a tag and its payload.

 Read the tag first, then the arm it selects. A tag this build does not
 recognise means skip this one value and carry on; it never means stop.
 */
typedef struct guatiao_value {
  /*
   One of the `GUATIAO_*` tag constants.
   */
  uint32_t tag;
  /*
   Reserved. Always written as zero, so the whole node is
   byte-comparable and a C caller has a named field to initialise.
   */
  uint32_t _pad;
  /*
   The payload the tag selects.
   */
  union guatiao_payload payload;
} guatiao_value;

/*
 One per-path mode override: what the *declarer* of an option knows
 that whoever merges two maps does not.
 */
typedef struct guatiao_merge_override {
  /*
   The dotted path this governs, matched exactly.
   */
  struct guatiao_str path;
  /*
   One of the `GUATIAO_MERGE_*` mode constants.
   */
  uint32_t mode;
} guatiao_merge_override;

/*
 Borrowed bytes: any content at all, NULs included.

 Same shape and the same check-the-length rule as `guatiao_str`; a
 separate type because "text" and "arbitrary bytes" are different
 promises and collapsing them loses the distinction at every call site.
 */
typedef struct guatiao_bytes {
  /*
   First byte. May be null or dangling when `len` is 0.
   */
  const uint8_t *ptr;
  /*
   Length in bytes.
   */
  size_t len;
} guatiao_bytes;

/*
 A borrowed sequence of values, in order.
 */
typedef struct guatiao_values {
  /*
   First element. May be null or dangling when `len` is 0.
   */
  const struct guatiao_value *ptr;
  /*
   Number of elements.
   */
  size_t len;
} guatiao_values;

/*
 A borrowed sequence of key/value pairs, in **insertion order**.

 Order is part of the contract, not an artefact: consumers render maps
 as forms, print them as tables and diff them in tests, and all three
 need it stable and meaningful.
 */
typedef struct guatiao_entries {
  /*
   First entry. May be null or dangling when `len` is 0.
   */
  const guatiao_entry *ptr;
  /*
   Number of entries.
   */
  size_t len;
} guatiao_entries;

/*
 A `*const T` where **null is a value, not a mistake**.

 Crosses as a plain `const T *` and costs a C caller nothing: this is a
 `repr(transparent)` newtype, so its size, alignment and calling
 convention are a pointer's. What it buys is on the Rust side. A bare
 `*const T` in a descriptor says nothing about whether null is
 expected, so every reader re-decides and one of them eventually
 decides wrong; this says it once, in the type.

 # The contract

 **Non-null means a well-formed `T` that outlives the read.** Nothing
 checks that, and nothing tries: it is the same class of promise as a
 vtable pointer, whose shape only the `kind` that defined it knows.
 Writing a non-null pointer to anything that is not a live `T` is
 undefined behaviour at the read, on whoever wrote it.
 */
typedef const struct guatiao_map *guatiao_map_ptr;

/*
 What the host tells a library about itself, on the way in.

 The allocator is here because a library that wants to build a tree the
 host will keep can build it in the host's own arena, and then the host
 frees it with nothing to remember. A library that would rather use its
 own passes its own; every owned container records which it was.
 */
typedef struct guatiao_host_info {
  /*
   `sizeof(guatiao_host_info)` as the host compiled it. Always first.
   */
  uint32_t struct_size;
  /*
   The envelope version the host speaks. See [`ABI_VERSION`].
   */
  uint32_t abi_version;
  /*
   Who the host is, for a library that registers different providers
   for different hosts.
   */
  struct guatiao_str host_id;
  /*
   The host's own version string, uninterpreted.
   */
  struct guatiao_str host_version;
  /*
   The host's allocator, or null. Borrowed for the call and for as
   long as anything built through it lives.
   */
  const struct guatiao_alloc *alloc;
  /*
   Anything else this host wants to say, as an ordinary value, or
   null. Conventionally a map.

   The escape hatch every envelope needs and no envelope can specify:
   a build id, a capability flag, a vendor's own key. A reader that
   does not know a key skips it, which is the rule the value model
   already has for a tag it does not know.

   **A pointer, because this struct is `Copy`** and every reader
   projects its fields with a bitwise read. A [`Map`] held INLINE
   would be copied by each of those reads, and a `Map` frees what it
   owns on drop — so every copy would be a second owner of one
   buffer. A pointer has no drop glue whatever it addresses.

   **Non-null means a well-formed map.** Nothing here checks that,
   and a library that writes a non-null pointer to anything else has
   caused undefined behaviour at the read. It is the same class of
   promise as [`vtable`](ProviderInfo::vtable), whose shape only the
   `kind` knows, and as the allocator's outliving everything built
   through it.

   Unlike [`config`](ProviderInfo::config), null and an empty map mean
   the same thing here — "nothing to add" has no second reading
   worth keeping apart.
   */
  guatiao_map_ptr meta;
} guatiao_host_info;

/*
 A borrowed sequence of kind names.

 # Why this one carries no stride

 [`Providers`] states its stride because a `ProviderInfo` can grow a
 field. A [`Str`] cannot: it declares no `struct_size`, so it has no
 mechanism to grow through and its layout is frozen by definition.
 Where there is no versioning there is no version skew, and the element
 size is the same number on both sides of the boundary.
 */
typedef struct guatiao_kinds {
  /*
   First name. May be null when `len` is 0.
   */
  const struct guatiao_str *ptr;
  /*
   How many.
   */
  size_t len;
} guatiao_kinds;

/*
 One thing a library offers.

 The envelope defines **no vtable of its own**. Whoever defines a
 `kind` defines what its vtable looks like, and this carries the
 pointer and the size the library compiled it at — so a host that knows
 the kind can check the size the same way it checks an allocator's, and
 a host that does not know the kind can list the provider without ever
 looking at the pointer.
 */
typedef struct guatiao_provider_info {
  /*
   `sizeof(guatiao_provider_info)` as the library compiled it.
   */
  uint32_t struct_size;
  /*
   Size of the struct `vtable` points at, as the library compiled it.
   Zero when there is no vtable.
   */
  uint32_t vtable_size;
  /*
   What sorts of thing this is: `"greeter"`, `"codec"`, whatever the
   host and the library have agreed.

   **A list, because one provider commonly serves several.** A crate
   that both discovers hosts and opens sessions to them is one
   implementation with one identity, and registering it twice to say
   so would make it two providers a host has to know are the same.

   Each is a **capability**, never a name: it says which vtable this
   provider speaks, so a host can ask for everything that speaks one.
   What identifies the provider is `id`. Empty is legal and means a
   provider that serves no vtable — pure data, reached by name.
   */
  struct guatiao_kinds kinds;
  /*
   This provider's own identifier, **unique across every provider a
   host loads**.

   Names an implementation rather than a protocol: `"pve_qemu"`,
   `"mdns"`. Conventionally `{library id}_{name}`, where the name is
   whatever the implementation is called in its own source — which is
   what makes an id unique without any central register.

   **A re-export keeps the ORIGINAL id.** Two libraries offering one
   provider is an ordinary thing; that they agree on its id is what
   lets a host notice it already has it and skip the second, rather
   than loading one implementation twice under two names.

   What a host files it under is that host's own key template, `%id`
   by default.
   */
  struct guatiao_str id;
  /*
   A name to show a person. May be empty, and a host that shows
   nothing to anybody ignores it.
   */
  struct guatiao_str display_name;
  /*
   The schema for this provider's configuration, as an ordinary
   value, or null when it takes none.

   Null rather than an empty map, so "declares no configuration" and
   "declares an empty one" stay different statements.
   */
  const struct guatiao_value *config;
  /*
   The function table, whose shape is the `kind`'s business. Null
   when the kind is pure data.
   */
  const void *vtable;
  /*
   Passed back to every call through the vtable, untouched.
   */
  void *ctx;
  /*
   Anything else this provider wants to say, as an ordinary value, or
   null. Conventionally a map.

   The escape hatch every envelope needs and no envelope can specify:
   a build id, a capability flag, a vendor's own key. A reader that
   does not know a key skips it, which is the rule the value model
   already has for a tag it does not know.

   **A pointer, because this struct is `Copy`** and every reader
   projects its fields with a bitwise read. A [`Map`] held INLINE
   would be copied by each of those reads, and a `Map` frees what it
   owns on drop — so every copy would be a second owner of one
   buffer. A pointer has no drop glue whatever it addresses.

   **Non-null means a well-formed map.** Nothing here checks that,
   and a library that writes a non-null pointer to anything else has
   caused undefined behaviour at the read. It is the same class of
   promise as [`vtable`](ProviderInfo::vtable), whose shape only the
   `kind` knows, and as the allocator's outliving everything built
   through it.

   Unlike [`config`](ProviderInfo::config), null and an empty map mean
   the same thing here — "nothing to add" has no second reading
   worth keeping apart.
   */
  guatiao_map_ptr meta;
  /*
   This provider's own version, or **empty to inherit the library's**.

   Empty is the common case and the right default: a provider shipped
   in its own library versions with it, and saying so twice is two
   numbers to keep in step. A provider states its own when it does not
   move with its library — a re-exported one, or one whose contract
   froze while the library around it went on.

   Declared **semver**. This crate compares it as a string and never
   parses it: ordering is a host's policy, applied with the semver
   library it already has.
   */
  struct guatiao_str version;
  /*
   Can this provider actually run **here, right now** — and if not,
   why not?

   Null means yes. A library that does not implement this is
   available, which is the right default and the common case: most
   providers are code that either loaded or did not.

   Otherwise it returns `true` for available and leaves `reason`
   untouched, or `false` and writes a borrowed [`Str`] through
   `reason` saying why. **A boolean return rather than an empty
   string**, so "available" and "unavailable, with nothing to say
   about it" stay different answers.

   # What this envelope does and does not define

   It defines the **slot**: the signature, when the reason is written,
   and how long it lives. It does **not** define what "available"
   means, when a host should ask, or what a host should do with a
   refusal — those are between a host and a library, like everything
   else a `kind` agrees.

   What this crate promises is only that it **never caches the
   answer**. A library may load an optional dependency, lose a device,
   or fail its own integrity check while a process runs, and a host
   that asked once at load time would be holding an answer from before
   any of that.

   # The reason must outlive every reader

   Point it at a literal in the library's image, or at something
   leaked once. **Never at a buffer shared by callers**: two threads
   asking the same provider at the same time would each read whatever
   the other had just written, and what comes back is a fragment with
   nothing reporting it. Immortal, per-call or per-thread — but not
   one slot everybody writes.

   Spelled out inline rather than through a type alias: cbindgen
   renders an aliased function-pointer field as an opaque struct used
   by value, which is an incomplete type that compiles nowhere.
   */
  bool (*available)(void *ctx, struct guatiao_str *reason);
} guatiao_provider_info;

/*
 A borrowed sequence of provider descriptors.

 A view, like every other `{ptr, len}` in this crate: the library owns
 the array.

 # Why it carries a stride

 **`struct_size` cannot version an array's element size.** Every
 descriptor here declares its own size and a reader guards each
 appended field against it — but that only places the fields *within*
 an element. Finding element `i` needs the size the LIBRARY laid the
 array out at, and a reader that assumed its own would land inside an
 element built before its newest slot existed, read whatever sits at
 that offset as a `struct_size`, and guard every field against a number
 it invented.

 So the library states the stride and a reader walks by bytes.
 */
typedef struct guatiao_providers {
  /*
   First descriptor. May be null when `len` is 0.
   */
  const struct guatiao_provider_info *ptr;
  /*
   How many.
   */
  size_t len;
  /*
   `sizeof(guatiao_provider_info)` as the LIBRARY compiled it, which
   is the array's stride in bytes.

   Always the element size, even for one element: a reader refuses a
   stride below [`ProviderInfo::floor`], and refuses an element whose
   own `struct_size` exceeds it, which would overlap its neighbour.
   */
  size_t stride;
} guatiao_providers;

/*
 What a library says about itself, on the way out.
 */
typedef struct guatiao_library_info {
  /*
   `sizeof(guatiao_library_info)` as the library compiled it.
   */
  uint32_t struct_size;
  /*
   The envelope version the library speaks.
   */
  uint32_t abi_version;
  /*
   A stable identifier for the library itself, for diagnostics and
   for refusing to load the same one twice.
   */
  struct guatiao_str id;
  /*
   Its version, declared **semver**.

   A field a host can name in the key it files providers under
   (`%version`), which is what lets two builds of one provider be
   loaded at once. This crate compares it as a string and never parses
   it — ordering is a host's policy, applied with the semver library
   it already has.
   */
  struct guatiao_str version;
  /*
   Everything it offers. May be empty, which is a library that
   loaded and had nothing for this host.
   */
  struct guatiao_providers providers;
  /*
   Anything else this library wants to say, as an ordinary value, or
   null. Conventionally a map.

   The escape hatch every envelope needs and no envelope can specify:
   a build id, a capability flag, a vendor's own key. A reader that
   does not know a key skips it, which is the rule the value model
   already has for a tag it does not know.

   **A pointer, because this struct is `Copy`** and every reader
   projects its fields with a bitwise read. A [`Map`] held INLINE
   would be copied by each of those reads, and a `Map` frees what it
   owns on drop — so every copy would be a second owner of one
   buffer. A pointer has no drop glue whatever it addresses.

   **Non-null means a well-formed map.** Nothing here checks that,
   and a library that writes a non-null pointer to anything else has
   caused undefined behaviour at the read. It is the same class of
   promise as [`vtable`](ProviderInfo::vtable), whose shape only the
   `kind` knows, and as the allocator's outliving everything built
   through it.

   Unlike [`config`](ProviderInfo::config), null and an empty map mean
   the same thing here — "nothing to add" has no second reading
   worth keeping apart.
   */
  guatiao_map_ptr meta;
} guatiao_library_info;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/*
 A new registry introducing its host as `id`/`version`.

 `alloc` may be null, and is the allocator offered to every library, so
 a tree a library builds for this host is built in the host's own arena.
 A library may ignore it and use its own; either way the tree carries
 the allocator that made it, so this host frees it correctly without
 knowing which.

 The two strings are **copied**, so they need not outlive this call.
 Returns null when one of them is not UTF-8, or when `alloc` is
 non-null and incomplete.

 # Safety

 `id` and `version` are views whose bytes are readable for this call,
 and `alloc` is null or a complete allocator that outlives every tree
 built through it.
 */
struct guatiao_registry *guatiao_registry_new(struct guatiao_str id,
                                              struct guatiao_str version,
                                              const struct guatiao_alloc *alloc);

/*
 Releases a registry. Null is a no-op.

 **The libraries it loaded stay mapped.** Nothing in this crate unloads
 one, because every tree, string and vtable they handed over points into
 their images; this frees the host's own table and nothing else.

 # Safety

 `reg` is null or a handle from [`guatiao_registry_new`] that has not
 already been freed, and nothing else is using it.
 */
void guatiao_registry_free(struct guatiao_registry *reg);

/*
 Names providers with `template` instead of `%id`.

 Anything already loaded is re-keyed. **A refusal changes nothing**: the
 keys are all rendered and checked before any is written.

 # Safety

 `reg` is a live handle and `template` is readable for this call.
 */
guatiao_status guatiao_registry_keyed_by(struct guatiao_registry *reg,
                                         struct guatiao_str template_);

/*
 Names libraries with `template` instead of `%id` — the "how many builds
 of one library may I hold" knob.

 # Safety

 As [`guatiao_registry_keyed_by`].
 */
guatiao_status guatiao_registry_libraries_keyed_by(struct guatiao_registry *reg,
                                                   struct guatiao_str template_);

/*
 Loads one file, writing what happened to `out` as a map.

 `{"loaded": <library>}` or `{"skipped": "<why>", "from": "<path>"}`,
 where `from` is present only when the reason has one. **A skip is an
 answer, not a failure**: the file is not a library, the library
 declined this host, or this registry already has it.

 **Mapping a library runs its static initialisers**, which may do
 anything, including abort the process. Name files you are willing to
 run.

 # Safety

 `reg` is a live handle, `path` and `alloc` are valid for this call, and
 `out` addresses writable storage for one value, whose previous contents
 are the caller's to have freed.
 */
guatiao_status guatiao_registry_load_file(struct guatiao_registry *reg,
                                          struct guatiao_str path,
                                          const struct guatiao_alloc *alloc,
                                          struct guatiao_value *out);

/*
 Scans a directory, writing a report to `out` as a map.

 `{"loaded": [path…], "skipped": [{"skipped", "path", "from"?}…],
 "failed": [{"path", "error"}…]}`.

 Nothing is opened that has not first been shown, **by reading its
 export table as data**, to declare the entry symbol — so a directory
 full of ordinary libraries costs no static initialisers.

 `descending` visits names highest-first, which under a `%id` library
 key is how a host takes the newest of several builds. That is byte
 order, not version order; nothing here parses a version.

 # Safety

 As [`guatiao_registry_load_file`], with `dir` naming a directory.
 */
guatiao_status guatiao_registry_scan_dir(struct guatiao_registry *reg,
                                         struct guatiao_str dir,
                                         bool descending,
                                         const struct guatiao_alloc *alloc,
                                         struct guatiao_value *out);

/*
 Every library loaded, as a list of maps.

 # Safety

 `reg` is a live handle, `alloc` is valid, and `out` addresses writable
 storage for one value.
 */
guatiao_status guatiao_registry_libraries(const struct guatiao_registry *reg,
                                          const struct guatiao_alloc *alloc,
                                          struct guatiao_value *out);

/*
 Every provider that serves `kind`, as a list of maps — or **every**
 provider when `kind` is empty.

 The capability question. [`guatiao_registry_provider`] is the identity
 one.

 # Safety

 As [`guatiao_registry_libraries`], with `kind` readable for the call.
 */
guatiao_status guatiao_registry_providers(const struct guatiao_registry *reg,
                                          struct guatiao_str kind,
                                          const struct guatiao_alloc *alloc,
                                          struct guatiao_value *out);

/*
 One provider by the key this registry filed it under, as a map.

 `GUATIAO_ERR_NOT_FOUND` when nothing answers to that key.

 # Safety

 As [`guatiao_registry_providers`], with `key` readable for the call.
 */
guatiao_status guatiao_registry_provider(const struct guatiao_registry *reg,
                                         struct guatiao_str key,
                                         const struct guatiao_alloc *alloc,
                                         struct guatiao_value *out);

/*
 Every provider serving `kind` that **can actually run here**, as a list
 of maps.

 [`guatiao_registry_providers`] is who CLAIMS the kind; this is who can
 serve it now. Each is asked at the moment of the call and nothing is
 cached, so a provider whose optional dependency arrived or went away
 since the last call answers differently — which is the point.

 # Safety

 As [`guatiao_registry_providers`].
 */
guatiao_status guatiao_registry_available(const struct guatiao_registry *reg,
                                          struct guatiao_str kind,
                                          const struct guatiao_alloc *alloc,
                                          struct guatiao_value *out);

/*
 Why nothing can serve `kind`, as a map.

 `{"available": true}` when something can. Otherwise
 `{"available": false, "why": "nothing-claims-it"}` or
 `{"available": false, "why": "none-available",
 "providers": [{"id", "reason"}…]}`.

 **The two refusals are kept apart because the remedies differ**:
 install something, versus fix what you already have. A single
 "unsupported" leaves a person with no idea which way to go.

 # Safety

 As [`guatiao_registry_providers`].
 */
guatiao_status guatiao_registry_why_not(const struct guatiao_registry *reg,
                                        struct guatiao_str kind,
                                        const struct guatiao_alloc *alloc,
                                        struct guatiao_value *out);

/*
 Whether one provider can run here, writing its reason through `reason`
 when it cannot.

 `true` when it can, or when no provider answers to `key` — a caller
 that cares about the difference has [`guatiao_registry_provider`],
 which reports `NOT_FOUND`. `reason` may be null, and is written only on
 a refusal; what it points at lives as long as the library.

 **Asked every time, never cached.**

 # Safety

 `reg` is a live handle, `key` is readable for the call, and `reason` is
 null or addresses writable storage for one `guatiao_str`.
 */
bool guatiao_registry_provider_available(const struct guatiao_registry *reg,
                                         struct guatiao_str key,
                                         struct guatiao_str *reason);

/*
 Ranks every provider with this id, now and whenever one loads.

 **This is how a host chooses between two implementations of one
 kind.** `guatiao_registry_providers` and `_available` answer best
 first, which is `(priority DESC, key ASC)` — the key tiebreak because
 load order follows directory iteration, which no filesystem promises
 to keep stable, so "whichever loaded first" is not a rule anyone can
 reproduce.

 Absent means 0, so an unranked provider sorts below any raised one and
 alongside every other unranked one. Negative ranks below them all.

 A frontend reads its own configuration and calls this; nothing in this
 library reads a file.

 # Safety

 `reg` is a live handle and `id` is readable for this call.
 */
guatiao_status guatiao_registry_set_priority(struct guatiao_registry *reg,
                                             struct guatiao_str id,
                                             int32_t priority);

/*
 What this host ranked that id. Zero unless it said otherwise, and zero
 for a null handle — a rank is not a lookup, and there is no answer to
 distinguish "unranked" from.

 # Safety

 `reg` is a live handle and `id` is readable for this call.
 */
int32_t guatiao_registry_priority(const struct guatiao_registry *reg, struct guatiao_str id);

/*
 The best provider serving `kind` that can actually run here, as a map.

 `GUATIAO_ERR_NOT_FOUND` when nothing can. The question a host usually
 has; `guatiao_registry_available` is how to see what it passed over,
 so a frontend can say "ssh -> openssh (also: putty)".

 # Safety

 As [`guatiao_registry_providers`].
 */
guatiao_status guatiao_registry_best(const struct guatiao_registry *reg,
                                     struct guatiao_str kind,
                                     const struct guatiao_alloc *alloc,
                                     struct guatiao_value *out);

/*
 One provider's function table, and the size the library compiled it at.

 Null when no provider answers to `key`, or when it declares no table.
 `size_out` may be null; when it is not, it receives the declared size.

 **This is the moment a caller takes on the kind's contract.** The
 envelope defines no vtable: check the declared size against the frozen
 floor of the `kind` you believe this is, project each field through the
 pointer, and guard every field appended after that floor. A shorter
 table than you expect is an OLDER library, which is the case the size
 exists to let you support rather than reject.

 The pointer stays valid for the life of the process, because a loaded
 library is never unloaded.

 # Safety

 `reg` is a live handle, `key` is readable for the call, and `size_out`
 is null or addresses writable storage for one `size_t`.
 */
const void *guatiao_registry_provider_vtable(const struct guatiao_registry *reg,
                                             struct guatiao_str key,
                                             size_t *size_out);

/*
 The context pointer to hand back to every call through that provider's
 table. Null is a legitimate answer and means the provider needs none.

 # Safety

 `reg` is a live handle and `key` is readable for the call.
 */
void *guatiao_registry_provider_ctx(const struct guatiao_registry *reg, struct guatiao_str key);

/*
 One provider's configuration schema, **borrowed** from the library's
 own image, or null when it declares none.

 Read it with the ordinary value readers: a schema is a value. Do not
 free it — it is not yours, and it lives as long as the process.

 # Safety

 `reg` is a live handle and `key` is readable for the call.
 */
const struct guatiao_value *guatiao_registry_provider_config(const struct guatiao_registry *reg,
                                                             struct guatiao_str key);

/*
 Merges `later` into `earlier`, later winning, and writes a new tree
 through `out`.

 Neither input is touched. The result is built entirely through
 `alloc`, which is also the allocator it frees through, so the caller
 releases it with `guatiao_value_free` and nothing else.

 `overrides` may be null when `overrides_len` is zero. `out_error` may
 be null, and receives a map describing the disagreement when the merge
 fails on one.

 # Safety

 Every non-null pointer addresses what its type says, `out` addresses
 writable storage for one value that does not already hold one the
 caller still owns, and `overrides` addresses `overrides_len` entries.
 */
guatiao_status guatiao_merge(uint32_t mode,
                             const struct guatiao_value *earlier,
                             const struct guatiao_value *later,
                             const struct guatiao_alloc *alloc,
                             uint32_t options,
                             const struct guatiao_merge_override *overrides,
                             size_t overrides_len,
                             struct guatiao_value *out,
                             struct guatiao_value *out_error);

/*
 Whether `config` is a value `schema` accepts.

 `out_error` may be null, and receives a map carrying the field's key
 and what would have been accepted — never the value that was refused,
 because a field may be marked sensitive and an error type that
 quotes its input is one that eventually logs a passphrase.

 # Safety

 Every non-null pointer addresses what its type says, and `out_error`
 addresses writable storage for one value.
 */
guatiao_status guatiao_schema_validate(const struct guatiao_value *schema,
                                       const struct guatiao_value *config,
                                       const struct guatiao_alloc *alloc,
                                       struct guatiao_value *out_error);

/*
 The field governing a flat key, or null.

 Follows one level of projection, so `auth.password` answers the arm
 field's own field rather than the `auth` field. Every per-field flag
 a caller wants — required, advanced, sensitive, the label — is read
 off the value this hands back, so the boundary needs one lookup rather
 than one export per flag.

 The result **borrows from `schema`** and is valid for as long as it is.

 # Safety

 `schema` addresses a well-formed value, and `key` a readable view.
 */
const struct guatiao_value *guatiao_schema_resolve(const struct guatiao_value *schema,
                                                   struct guatiao_str key);

/*
 The flat keys one field projects onto, as a list of strings.

 # Safety

 `field` addresses a well-formed field value and `out` writable
 storage for one value.
 */
guatiao_status guatiao_schema_flat_keys(const struct guatiao_value *field,
                                        const struct guatiao_alloc *alloc,
                                        struct guatiao_value *out);

/*
 Writes a tagged value into a flat store of `key -> text`.

 `GUATIAO_ERR_WRONG_KIND` when the field is not a variant or the value
 is not a map, which is the same "it does not apply" the Rust side
 reports as `false`.

 # Safety

 Every non-null pointer addresses what its type says, and `out`
 addresses writable storage for one value.
 */
guatiao_status guatiao_schema_flatten(const struct guatiao_value *field,
                                      const struct guatiao_value *value,
                                      const struct guatiao_alloc *alloc,
                                      struct guatiao_value *out);

/*
 Rebuilds a tagged value from a flat store.

 The reverse of [`guatiao_schema_flatten`], and the round trip is what
 makes the projection usable: a front end reads text, hands it back, and
 gets the value the schema describes.

 # Safety

 As for [`guatiao_schema_flatten`]. `flat` is a map whose values are all
 strings; one that is not answers `GUATIAO_ERR_WRONG_KIND`.
 */
guatiao_status guatiao_schema_unflatten(const struct guatiao_value *field,
                                        const struct guatiao_value *flat,
                                        const struct guatiao_alloc *alloc,
                                        struct guatiao_value *out);

/*
 Frees everything `v` owns and leaves it null-tagged.

 Safe to call twice, and safe on a value that owns nothing.

 # Safety

 `v` is null, or addresses a well-formed value nothing else is freeing.
 */
guatiao_status guatiao_value_free(struct guatiao_value *v);

/*
 Deep-copies `src` into `alloc`, writing the copy through `out`.

 # Safety

 The pointers are null or valid, and `out` addresses writable storage
 for one value that does not already hold one.
 */
guatiao_status guatiao_value_clone(const struct guatiao_alloc *alloc,
                                   const struct guatiao_value *src,
                                   struct guatiao_value *out);

/*
 Writes the stored nothing through `out`.

 # Safety

 `out` addresses writable storage for one value.
 */
guatiao_status guatiao_value_null(struct guatiao_value *out);

/*
 Writes the absent marker through `out` -- the answer to a lookup that
 found nothing, and the tag of an optional slot left empty.

 # Safety

 `out` addresses writable storage for one value.
 */
guatiao_status guatiao_value_absent(struct guatiao_value *out);

/*
 Writes a boolean through `out`. Any non-zero `b` is true.

 # Why this takes a byte and not a `bool`

 A Rust `bool` must be 0 or 1, and a value outside that is undefined
 behaviour **at the moment it arrives**, before this function's body
 runs and before anything could reject it. A C caller can produce one
 without trying: through a cast, a union, or an uninitialised local.

 So the boundary takes the primitive and this crate decides, which is
 the same rule the tag follows. It costs a C caller nothing —
 `guatiao_value_bool(true, &v)` still compiles and still means true.

 # Safety

 `out` addresses writable storage for one value.
 */
guatiao_status guatiao_value_bool(uint8_t b, struct guatiao_value *out);

/*
 Writes an empty map through `out`, to be grown through `alloc`.

 # Safety

 The pointers are null or valid, and `out` addresses writable storage.
 */
guatiao_status guatiao_value_map(const struct guatiao_alloc *alloc, struct guatiao_value *out);

/*
 Writes an empty list through `out`, to be grown through `alloc`.

 # Safety

 The pointers are null or valid, and `out` addresses writable storage.
 */
guatiao_status guatiao_value_list(const struct guatiao_alloc *alloc, struct guatiao_value *out);

/*
 Copies `text` into a new string value, through `out`.

 Refuses anything that is not UTF-8: a string is UTF-8 by contract, so a
 reader can hand back text without re-checking at every access. Content
 that is not text belongs in `guatiao_value_bytes`.

 # Safety

 The pointers are null or valid, the view's bytes are readable for the
 call, and `out` addresses writable storage.
 */
guatiao_status guatiao_value_string(const struct guatiao_alloc *alloc,
                                    struct guatiao_str text,
                                    struct guatiao_value *out);

/*
 Copies `text` into a new number value, through `out`, storing it
 **verbatim**.

 Refuses anything outside the JSON number grammar, at construction
 rather than at read.

 # Safety

 The pointers are null or valid, the view's bytes are readable for the
 call, and `out` addresses writable storage.
 */
guatiao_status guatiao_value_number(const struct guatiao_alloc *alloc,
                                    struct guatiao_str text,
                                    struct guatiao_value *out);

/*
 Copies `bytes` into a new bytes value, through `out`. Any content at
 all, NULs included.

 # Safety

 The pointers are null or valid, the view's bytes are readable for the
 call, and `out` addresses writable storage.
 */
guatiao_status guatiao_value_bytes(const struct guatiao_alloc *alloc,
                                   struct guatiao_bytes bytes,
                                   struct guatiao_value *out);

/*
 Stores `value` under `key`, **moving** it and leaving it null-tagged.

 Replaces any existing entry in place, keeping its position. To store
 something you only borrowed, call `guatiao_value_clone` first and pass
 the copy: there is no copying variant, so the cost is always a line you
 can see.

 # Safety

 The pointers are null or valid, and the key's bytes are readable.
 */
guatiao_status guatiao_map_set(const struct guatiao_alloc *alloc,
                               struct guatiao_value *node,
                               struct guatiao_str key,
                               struct guatiao_value *value);

/*
 Removes `key` and frees its value. `GUATIAO_ERR_NOT_FOUND` if absent.

 # Safety

 The pointers are null or valid, and the key's bytes are readable.
 */
guatiao_status guatiao_map_discard(struct guatiao_value *node, struct guatiao_str key);

/*
 Frees every entry and empties the map, keeping its capacity.

 # Safety

 `node` is null or a well-formed map.
 */
guatiao_status guatiao_map_clear(struct guatiao_value *node);

/*
 Copies every entry of `src` into `dst`, replacing collisions.

 **Use this before rebuilding a record**, or every field you do not
 model is dropped on write-back.

 # Safety

 The pointers are null or valid.
 */
guatiao_status guatiao_map_copy_from(const struct guatiao_alloc *alloc,
                                     struct guatiao_value *dst,
                                     const struct guatiao_value *src);

/*
 Appends `value`, **moving** it and leaving it null-tagged.

 To append something you only borrowed, call `guatiao_value_clone`
 first and pass the copy.

 # Safety

 The pointers are null or valid.
 */
guatiao_status guatiao_list_push(const struct guatiao_alloc *alloc,
                                 struct guatiao_value *node,
                                 struct guatiao_value *value);

/*
 Removes and frees the element at `index`.

 # Safety

 `node` is null or a well-formed list.
 */
guatiao_status guatiao_list_discard(struct guatiao_value *node, size_t index);

/*
 Frees every element and empties the list, keeping its capacity.

 # Safety

 `node` is null or a well-formed list.
 */
guatiao_status guatiao_list_clear(struct guatiao_value *node);

/*
 Appends UTF-8 text to a string value.

 # Safety

 The pointers are null or valid and the view's bytes are readable.
 */
guatiao_status guatiao_string_push(const struct guatiao_alloc *alloc,
                                   struct guatiao_value *node,
                                   struct guatiao_str text);

/*
 Appends to a bytes value.

 # Safety

 The pointers are null or valid and the view's bytes are readable.
 */
guatiao_status guatiao_buffer_push(const struct guatiao_alloc *alloc,
                                   struct guatiao_value *node,
                                   struct guatiao_bytes bytes);

/*
 The allocator over Rust's global allocator, for a C caller that has no
 reason to supply its own.

 Writes it through `out`. The caller keeps the struct alive for as long
 as any tree built through it: containers hold a pointer to it.

 # Safety

 `out` addresses writable storage for one allocator.
 */
guatiao_status guatiao_alloc_default(struct guatiao_alloc *out);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* GUATIAO_H */

/* ======================================================================
 * guatiao_entry, and the accessors that need nothing linked.
 * ====================================================================== */

#ifndef GUATIAO_ENTRY_DEFINED
#define GUATIAO_ENTRY_DEFINED

/*
 One key/value pair of a map. The value is held INLINE, not by pointer, so
 a map is one contiguous array.

 Defined here rather than above because the type graph is cyclic and a
 generator cannot order it for C; see the forward declaration near the top.
 Its layout is pinned by the static assertions a consumer can copy from
 this crate's own C test.
 */
struct guatiao_entry {
  /* Raw bytes. No case folding, no normalisation: "Host" and "host" are
     two keys, and a key may contain a NUL. */
  guatiao_string key;
  guatiao_value value;
};

/* ---- views out of owned containers ---------------------------------- */

static inline guatiao_str guatiao_string_view(const guatiao_string *s) {
  guatiao_str out;
  out.ptr = s ? s->ptr : NULL;
  out.len = s ? s->len : 0;
  return out;
}

static inline guatiao_bytes guatiao_buffer_view(const guatiao_buffer *b) {
  guatiao_bytes out;
  out.ptr = b ? b->ptr : NULL;
  out.len = b ? b->len : 0;
  return out;
}

static inline guatiao_values guatiao_list_view(const guatiao_list *l) {
  guatiao_values out;
  out.ptr = l ? l->ptr : NULL;
  out.len = l ? l->len : 0;
  return out;
}

static inline guatiao_entries guatiao_map_view(const guatiao_map *m) {
  guatiao_entries out;
  out.ptr = m ? m->ptr : NULL;
  out.len = m ? m->len : 0;
  return out;
}

/* ---- building a view from your own memory --------------------------- */

static inline guatiao_str guatiao_str_from(const char *p, size_t len) {
  guatiao_str out;
  out.ptr = (const uint8_t *)p;
  out.len = len;
  return out;
}

/* From a NUL-terminated C string. The NUL is NOT stored: guatiao strings
   carry an explicit length, so this is a convenience for callers who
   happen to have a `char *`, not the storage format. */
static inline guatiao_str guatiao_cstr(const char *p) {
  return guatiao_str_from(p, p ? strlen(p) : 0);
}

static inline guatiao_bytes guatiao_bytes_from(const void *p, size_t len) {
  guatiao_bytes out;
  out.ptr = (const uint8_t *)p;
  out.len = len;
  return out;
}

/* ---- reading a value ------------------------------------------------- */

/* Every accessor below answers for a NULL value rather than faulting: a
   null is the first thing that arrives when a preceding call failed and
   its result went unchecked, and faulting there loses the real error. */

static inline uint32_t guatiao_tag_of(const guatiao_value *v) {
  return v ? v->tag : (uint32_t)GUATIAO_ABSENT;
}

/* The exact text of a NUMBER, verbatim. Empty for any other kind.

   THIS IS THE ACCESSOR THAT CANNOT LIE. A number is stored as the text
   that declared it, so "1.10" reads back as "1.10" and a 200-digit
   integer survives -- nothing ever converted it. */
static inline guatiao_str guatiao_number_text(const guatiao_value *v) {
  guatiao_str out;
  out.ptr = NULL;
  out.len = 0;
  if (v && v->tag == (uint32_t)GUATIAO_NUMBER) {
    out = guatiao_string_view(&v->payload.text);
  }
  return out;
}

/* The text of a STRING. Empty for any other kind, a NUMBER included: the
   kinds are distinct and nothing coerces between them. */
static inline guatiao_str guatiao_string_text(const guatiao_value *v) {
  guatiao_str out;
  out.ptr = NULL;
  out.len = 0;
  if (v && v->tag == (uint32_t)GUATIAO_STRING) {
    out = guatiao_string_view(&v->payload.text);
  }
  return out;
}

static inline guatiao_bytes guatiao_bytes_data(const guatiao_value *v) {
  guatiao_bytes out;
  out.ptr = NULL;
  out.len = 0;
  if (v && v->tag == (uint32_t)GUATIAO_BYTES) {
    out = guatiao_buffer_view(&v->payload.bytes);
  }
  return out;
}

static inline guatiao_values guatiao_list_items(const guatiao_value *v) {
  guatiao_values out;
  out.ptr = NULL;
  out.len = 0;
  if (v && v->tag == (uint32_t)GUATIAO_LIST) {
    out = guatiao_list_view(&v->payload.list);
  }
  return out;
}

static inline guatiao_entries guatiao_map_entries(const guatiao_value *v) {
  guatiao_entries out;
  out.ptr = NULL;
  out.len = 0;
  if (v && v->tag == (uint32_t)GUATIAO_MAP) {
    out = guatiao_map_view(&v->payload.map);
  }
  return out;
}

/* ---- lookup ---------------------------------------------------------- */

/* Byte equality. USE THIS, NOT strcmp: a key carries an explicit length
   and may contain a NUL, so strcmp would report two different keys as the
   same one. */
static inline bool guatiao_str_eq(guatiao_str a, guatiao_str b) {
  if (a.len != b.len) {
    return false;
  }
  if (a.len == 0) {
    return true;
  }
  return memcmp(a.ptr, b.ptr, a.len) == 0;
}

static inline guatiao_str guatiao_entry_key(const guatiao_entry *e) {
  guatiao_str out;
  out.ptr = NULL;
  out.len = 0;
  if (e) {
    out = guatiao_string_view(&e->key);
  }
  return out;
}

/* The value under `key`, or NULL. Linear, which is the right shape for a
   metadata container of tens of keys held in contiguous memory. */
static inline const guatiao_value *guatiao_map_find(const guatiao_value *v,
                                                    guatiao_str key) {
  guatiao_entries es = guatiao_map_entries(v);
  size_t i;
  for (i = 0; i < es.len; i++) {
    if (guatiao_str_eq(guatiao_entry_key(&es.ptr[i]), key)) {
      return &es.ptr[i].value;
    }
  }
  return NULL;
}

static inline const guatiao_value *guatiao_list_at(const guatiao_value *v,
                                                   size_t index) {
  guatiao_values items = guatiao_list_items(v);
  return index < items.len ? &items.ptr[index] : NULL;
}

/* ---- typed reads, with a caller's default ---------------------------- */

/* Each of these collapses absent, wrong-kind and not-representable into
   the caller's default, which is right for the overwhelmingly common call.
   A caller that must tell them apart has guatiao_tag_of() and
   guatiao_number_text(), which hands back the exact text whatever its
   magnitude. */

/* Any non-zero byte is true. The arm is a uint8_t rather than a _Bool
   precisely so that this read is defined for every byte a producer could
   have put there; see the field's note above. */
static inline bool guatiao_bool_or(const guatiao_value *v, bool fallback) {
  if (!v || v->tag != (uint32_t)GUATIAO_BOOL) {
    return fallback;
  }
  return v->payload.b != 0;
}

/*
 A number as an int64_t, or `fallback`.

 IT NEVER TRUNCATES, and that is the whole reason this exists rather than
 leaving every consumer to call strtoll. `fallback` is answered for a
 value outside int64_t's range, one with a fractional part, and one
 written with an exponent -- `1e2` is integral in value but not in
 spelling, and evaluating the exponent correctly for arbitrary precision
 is the arithmetic this container exists to avoid. strtoll would instead
 SATURATE to LLONG_MAX and set errno, which is a wrong answer that looks
 like a right one.
 */
static inline int64_t guatiao_int_or(const guatiao_value *v, int64_t fallback) {
  guatiao_str t = guatiao_number_text(v);
  char buf[48];
  char *end = NULL;
  long long parsed;
  size_t i;
  if (t.len == 0 || t.len >= sizeof(buf)) {
    return fallback;
  }
  for (i = 0; i < t.len; i++) {
    char c = (char)t.ptr[i];
    if (c == '.' || c == 'e' || c == 'E') {
      return fallback; /* fractional or exponent: not an integer spelling */
    }
    buf[i] = c;
  }
  buf[t.len] = '\0';
  errno = 0;
  parsed = strtoll(buf, &end, 10);
  if (errno != 0 || end != buf + t.len) {
    return fallback;
  }
  return (int64_t)parsed;
}

/*
 A number as the nearest double, or `fallback` when there is no finite one.

 Lossy by construction: a double has 53 bits of mantissa, so a value
 needing more comes back rounded and nothing here reports it.
 */
static inline double guatiao_float_or(const guatiao_value *v, double fallback) {
  guatiao_str t = guatiao_number_text(v);
  char buf[344]; /* wide enough for any double's decimal spelling */
  char *end = NULL;
  double parsed;
  if (t.len == 0 || t.len >= sizeof(buf)) {
    return fallback;
  }
  memcpy(buf, t.ptr, t.len);
  buf[t.len] = '\0';
  errno = 0;
  parsed = strtod(buf, &end);
  if (end != buf + t.len || errno == ERANGE) {
    return fallback;
  }
  return parsed;
}

/* ---- writing a tree as a literal ------------------------------------- */

/*
 A statically declared value. Every owned field gets cap 0 and a NULL
 allocator, which is what marks the storage as NOT OURS: such a buffer is
 never freed, so a literal tree may be passed to guatiao_value_free()
 safely, and the first append copies out of it and leaves it untouched.

 C only. A C++ caller builds the same thing with the functions above.
 */
#ifndef __cplusplus

#define GUATIAO_STRING_LIT(lit) \
  { (uint8_t *)(lit), sizeof(lit) - 1, 0, NULL }

#define GUATIAO_VALUE_STRING_LIT(lit) \
  { (uint32_t)GUATIAO_STRING, 0, { .text = GUATIAO_STRING_LIT(lit) } }

#define GUATIAO_VALUE_NUMBER_LIT(lit) \
  { (uint32_t)GUATIAO_NUMBER, 0, { .text = GUATIAO_STRING_LIT(lit) } }

#define GUATIAO_VALUE_BOOL_LIT(v) \
  { (uint32_t)GUATIAO_BOOL, 0, { .b = (uint8_t)((v) ? 1 : 0) } }

#define GUATIAO_VALUE_NULL_LIT \
  { (uint32_t)GUATIAO_NULL, 0, { .b = 0 } }

/* A map or list over an array you declared yourself. */
#define GUATIAO_VALUE_MAP_LIT(arr) \
  { (uint32_t)GUATIAO_MAP, 0, \
    { .map = { (guatiao_entry *)(arr), sizeof(arr) / sizeof((arr)[0]), 0, NULL } } }

#define GUATIAO_VALUE_LIST_LIT(arr) \
  { (uint32_t)GUATIAO_LIST, 0, \
    { .list = { (guatiao_value *)(arr), sizeof(arr) / sizeof((arr)[0]), 0, NULL } } }

/* A byte array you declared yourself. */
#define GUATIAO_VALUE_BYTES_LIT(arr)   { (uint32_t)GUATIAO_BYTES, 0,     { .bytes = { (uint8_t *)(arr), sizeof(arr), 0, NULL } } }

/* Variadic, and it has to be: a value literal is a brace list, and a brace
   list handed to a fixed-arity macro splits at its own commas. */
#define GUATIAO_ENTRY_LIT(k, ...) { GUATIAO_STRING_LIT(k), __VA_ARGS__ }

/*
 An allocator over the C library, for a caller with no reason to supply
 its own. It must outlive every tree built through it.

 malloc guarantees only max_align_t, which is enough for every type this
 header declares and is asserted as such in this crate's own C test. Do
 NOT pair _aligned_malloc with free here: the two slots are a matched
 pair, and mixing them corrupts the heap.
 */
#define GUATIAO_ALLOC_MALLOC \
  { (uint32_t)sizeof(guatiao_alloc), NULL, \
    guatiao_malloc_alloc, guatiao_malloc_free, NULL }

static inline void *guatiao_malloc_alloc(void *ctx, size_t size, size_t align) {
  (void)ctx;
  (void)align;
  return size ? malloc(size) : NULL;
}

static inline void guatiao_malloc_free(void *ctx, void *p, size_t size,
                                       size_t align) {
  (void)ctx;
  (void)size;
  (void)align;
  free(p);
}

#endif /* __cplusplus */

#endif /* GUATIAO_ENTRY_DEFINED */
